'use client';
/**
 * Saguaro Field — Safety Incidents & Corrective Actions
 * Report incidents, track corrective actions, manage safety from the field. Offline queue.
 */
import React, { useState, useEffect, useRef, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { enqueue } from '@/lib/field-db';
import EmailComposer from '@/components/EmailComposer';

const GOLD   = '#C8960F';
const RAISED = '#0D1D2E';
const BORDER = '#1E3A5F';
const TEXT   = '#F0F4FF';
const DIM    = '#8BAAC8';
const GREEN  = '#22C55E';
const RED    = '#EF4444';
const AMBER  = '#F59E0B';
const BLUE   = '#3B82F6';

const INCIDENT_TYPES = ['near_miss', 'first_aid', 'recordable', 'lost_time'];
const TYPE_LABELS: Record<string, string> = { near_miss: 'Near Miss', first_aid: 'First Aid', recordable: 'Recordable', lost_time: 'Lost Time' };
const TYPE_COLORS: Record<string, string> = { near_miss: BLUE, first_aid: AMBER, recordable: RED, lost_time: '#DC2626' };

const CA_STATUSES = ['open', 'in_progress', 'verified', 'closed'];
const CA_STATUS_LABELS: Record<string, string> = { open: 'Open', in_progress: 'In Progress', verified: 'Verified', closed: 'Closed' };
const CA_STATUS_COLORS: Record<string, string> = { open: RED, in_progress: AMBER, verified: BLUE, closed: GREEN };

const SEVERITY_COLORS = ['#3B82F6', '#22C55E', '#F59E0B', '#EF4444', '#DC2626'];

interface CorrectiveAction {
  id: string;
  description: string;
  assigned_to?: string;
  due_date?: string;
  status: string;
  created_at?: string;
}

interface Incident {
  id: string;
  date: string;
  type: string;
  description: string;
  location?: string;
  severity: number;
  status?: string;
  corrective_actions?: CorrectiveAction[];
  photo_urls?: string[];
  created_at?: string;
}

type View = 'list' | 'detail' | 'create' | 'add_ca';

function formatDate(d: string | undefined): string {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

const exportPDF = (title: string, content: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1a1a1a; max-width: 800px; margin: 0 auto; }
        h1 { font-size: 24px; border-bottom: 2px solid #C8960F; padding-bottom: 8px; }
        h2 { font-size: 18px; color: #333; margin-top: 24px; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; font-size: 13px; }
        th { background: #f5f5f5; font-weight: 600; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
        .meta { color: #666; font-size: 13px; }
        .section { margin: 16px 0; padding: 12px; border: 1px solid #eee; border-radius: 8px; }
        img { max-width: 300px; margin: 4px; border-radius: 4px; }
        .signature { max-width: 200px; border: 1px solid #ddd; border-radius: 4px; padding: 4px; }
        .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">
        <p>Generated by Saguaro Control &middot; ${new Date().toLocaleString()}</p>
      </div>
    </body>
    </html>
  `);
  printWindow.document.close();
  setTimeout(() => printWindow.print(), 500);
};

const PdfIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}>
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1={12} y1={18} x2={12} y2={12}/><polyline points="9 15 12 12 15 15"/>
  </svg>
);

function SafetyPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const projectId = searchParams.get('projectId') || '';

  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [loading, setLoading] = useState(true);
  const [view, setView] = useState<View>('list');
  const [selected, setSelected] = useState<Incident | null>(null);
  const [online, setOnline] = useState(true);
  const [projectName, setProjectName] = useState('');
  const [saving, setSaving] = useState(false);
  const [actionMsg, setActionMsg] = useState('');
  const [showEmail, setShowEmail] = useState(false);

  // Bulk selection state
  const [selectMode, setSelectMode] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [bulkProcessing, setBulkProcessing] = useState(false);
  const [confirmDialog, setConfirmDialog] = useState<{ title: string; message: string; action: () => void } | null>(null);
  const [showBulkCA, setShowBulkCA] = useState(false);
  const [bulkCADesc, setBulkCADesc] = useState('');
  const [bulkCAAssigned, setBulkCAAssigned] = useState('');
  const [bulkCADueDate, setBulkCADueDate] = useState('');

  const toggleSelectId = (id: string) => {
    setSelectedIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };
  const selectAll = () => setSelectedIds(new Set(incidents.map(i => i.id)));
  const deselectAll = () => setSelectedIds(new Set());

  const handleBulkCloseIncidents = async () => {
    setBulkProcessing(true);
    const ids = Array.from(selectedIds);
    for (const id of ids) {
      try {
        if (!online) throw new Error('offline');
        await fetch(`/api/projects/${projectId}/safety/${id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ status: 'closed' }),
        });
      } catch {
        await enqueue({
          url: `/api/projects/${projectId}/safety/${id}`,
          method: 'PATCH',
          body: JSON.stringify({ status: 'closed' }),
          contentType: 'application/json',
          isFormData: false,
        });
      }
    }
    setIncidents(prev => prev.map(i => ids.includes(i.id) ? { ...i, status: 'closed' } : i));
    setSelectedIds(new Set());
    setSelectMode(false);
    setBulkProcessing(false);
    setActionMsg(`${ids.length} incident(s) closed`);
    setTimeout(() => setActionMsg(''), 3500);
  };

  const handleBulkAssignCA = async () => {
    if (!bulkCADesc.trim()) return;
    setBulkProcessing(true);
    const ids = Array.from(selectedIds);
    for (const id of ids) {
      const payload = {
        incident_id: id,
        description: bulkCADesc.trim(),
        assigned_to: bulkCAAssigned.trim() || null,
        due_date: bulkCADueDate || null,
      };
      try {
        if (!online) throw new Error('offline');
        await fetch(`/api/projects/${projectId}/safety/corrective-actions`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
      } catch {
        await enqueue({
          url: `/api/projects/${projectId}/safety/corrective-actions`,
          method: 'POST',
          body: JSON.stringify(payload),
          contentType: 'application/json',
          isFormData: false,
        });
      }
    }
    // Optimistic local update
    const newCA: CorrectiveAction = {
      id: `bulk-ca-${Date.now()}`,
      description: bulkCADesc.trim(),
      assigned_to: bulkCAAssigned.trim() || undefined,
      due_date: bulkCADueDate || undefined,
      status: 'open',
      created_at: new Date().toISOString(),
    };
    setIncidents(prev => prev.map(i => ids.includes(i.id) ? { ...i, corrective_actions: [...(i.corrective_actions || []), { ...newCA, id: `${newCA.id}-${i.id}` }] } : i));
    setSelectedIds(new Set());
    setSelectMode(false);
    setShowBulkCA(false);
    setBulkCADesc('');
    setBulkCAAssigned('');
    setBulkCADueDate('');
    setBulkProcessing(false);
    setActionMsg(`Corrective action assigned to ${ids.length} incident(s)`);
    setTimeout(() => setActionMsg(''), 3500);
  };

  const handleBulkExportIncidents = async () => {
    setBulkProcessing(true);
    const ids = Array.from(selectedIds);
    try {
      if (!online) throw new Error('offline');
      const res = await fetch(`/api/projects/${projectId}/safety/export`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ incident_ids: ids }),
      });
      if (res.ok) {
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `safety-report-${Date.now()}.pdf`;
        a.click();
        URL.revokeObjectURL(url);
        setActionMsg(`${ids.length} incident(s) exported`);
      } else {
        setActionMsg('Export failed');
      }
    } catch {
      await enqueue({
        url: `/api/projects/${projectId}/safety/export`,
        method: 'POST',
        body: JSON.stringify({ incident_ids: ids }),
        contentType: 'application/json',
        isFormData: false,
      });
      setActionMsg('Export queued — will download when online');
    }
    setSelectedIds(new Set());
    setSelectMode(false);
    setBulkProcessing(false);
    setTimeout(() => setActionMsg(''), 3500);
  };

  // Create incident form
  const [newDate, setNewDate] = useState(new Date().toISOString().slice(0, 10));
  const [newType, setNewType] = useState<string>('near_miss');
  const [newDesc, setNewDesc] = useState('');
  const [newLocation, setNewLocation] = useState('');
  const [newSeverity, setNewSeverity] = useState(1);
  const [newCA, setNewCA] = useState('');

  // Photo attachment
  const photoRef = useRef<HTMLInputElement>(null);
  const [photoPreviews, setPhotoPreviews] = useState<string[]>([]);
  const [photoFiles, setPhotoFiles] = useState<File[]>([]);

  // Add corrective action form
  const [caDesc, setCaDesc] = useState('');
  const [caAssigned, setCaAssigned] = useState('');
  const [caDueDate, setCaDueDate] = useState('');

  const handlePhotoCapture = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (!files.length) return;
    files.forEach((file) => {
      const reader = new FileReader();
      reader.onload = (ev) => {
        setPhotoPreviews((prev) => [...prev, String(ev.target?.result || '')]);
        setPhotoFiles((prev) => [...prev, file]);
      };
      reader.readAsDataURL(file);
    });
    e.target.value = '';
  };

  const removePhoto = (idx: number) => {
    setPhotoPreviews((prev) => prev.filter((_, i) => i !== idx));
    setPhotoFiles((prev) => prev.filter((_, i) => i !== idx));
  };

  const uploadPhotos = async (): Promise<string[]> => {
    const urls: string[] = [];
    for (const file of photoFiles) {
      try {
        const fd = new FormData();
        fd.append('file', file, file.name);
        fd.append('category', 'Safety');
        fd.append('caption', newDesc.trim().slice(0, 80));
        if (projectId) fd.append('projectId', projectId);
        const res = await fetch('/api/photos/upload', { method: 'POST', body: fd });
        if (res.ok) {
          const data = await res.json();
          urls.push(String(data.photo?.url || ''));
        }
      } catch { /* skip failed uploads */ }
    }
    return urls;
  };

  useEffect(() => {
    setOnline(navigator.onLine);
    const on = () => setOnline(true);
    const off = () => setOnline(false);
    window.addEventListener('online', on);
    window.addEventListener('offline', off);
    return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off); };
  }, []);

  useEffect(() => {
    if (!projectId) { setLoading(false); return; }
    fetch('/api/projects/list')
      .then((r) => r.ok ? r.json() : null)
      .then((d) => { const p = d?.projects?.find((x: { id: string; name: string }) => x.id === projectId); if (p) setProjectName(p.name); })
      .catch(() => {});
    loadIncidents();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId]);

  const loadIncidents = async () => {
    setLoading(true);
    try {
      const r = await fetch(`/api/projects/${projectId}/safety`);
      const d = await r.json();
      setIncidents(d.incidents || d.items || d.data || []);
    } catch { /* offline */ }
    setLoading(false);
  };

  const openDetail = (incident: Incident) => {
    setSelected(incident);
    setView('detail');
    setActionMsg('');
  };

  const handleCreateIncident = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newDesc.trim()) return;
    setSaving(true);

    // Upload photos first if online
    let photoUrls: string[] = [];
    if (photoFiles.length > 0 && online) {
      photoUrls = await uploadPhotos();
    }

    const payload = {
      projectId,
      date: newDate,
      type: newType,
      description: newDesc.trim(),
      location: newLocation.trim(),
      severity: newSeverity,
      corrective_action: newCA.trim() || null,
      photo_urls: photoUrls,
    };

    try {
      if (!online) throw new Error('offline');
      const res = await fetch(`/api/projects/${projectId}/safety`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error('Failed');
      await loadIncidents();
    } catch {
      await enqueue({
        url: `/api/projects/${projectId}/safety`,
        method: 'POST',
        body: JSON.stringify(payload),
        contentType: 'application/json',
        isFormData: false,
      });
      const localIncident: Incident = {
        id: `local-${Date.now()}`,
        date: newDate,
        type: newType,
        description: newDesc.trim(),
        location: newLocation.trim(),
        severity: newSeverity,
        status: 'open',
        corrective_actions: newCA.trim() ? [{ id: `local-ca-${Date.now()}`, description: newCA.trim(), status: 'open' }] : [],
        photo_urls: photoPreviews,
        created_at: new Date().toISOString(),
      };
      setIncidents((prev) => [localIncident, ...prev]);
    }

    resetCreateForm();
    setView('list');
    setSaving(false);
  };

  const resetCreateForm = () => {
    setNewDate(new Date().toISOString().slice(0, 10));
    setNewType('near_miss');
    setNewDesc('');
    setNewLocation('');
    setNewSeverity(1);
    setNewCA('');
    setPhotoPreviews([]);
    setPhotoFiles([]);
  };

  const handleAddCA = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selected || !caDesc.trim()) return;
    setSaving(true);

    const payload = {
      incident_id: selected.id,
      description: caDesc.trim(),
      assigned_to: caAssigned.trim() || null,
      due_date: caDueDate || null,
    };

    try {
      if (!online) throw new Error('offline');
      const res = await fetch(`/api/projects/${projectId}/safety/corrective-actions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error('Failed');
      const data = await res.json().catch(() => ({}));
      const newAction: CorrectiveAction = {
        id: data.id || `temp-${Date.now()}`,
        description: caDesc.trim(),
        assigned_to: caAssigned.trim() || undefined,
        due_date: caDueDate || undefined,
        status: 'open',
        created_at: new Date().toISOString(),
      };
      const updatedIncident = { ...selected, corrective_actions: [...(selected.corrective_actions || []), newAction] };
      setSelected(updatedIncident);
      setIncidents((prev) => prev.map((i) => i.id === selected.id ? updatedIncident : i));
      setActionMsg('Corrective action added');
    } catch {
      await enqueue({
        url: `/api/projects/${projectId}/safety/corrective-actions`,
        method: 'POST',
        body: JSON.stringify(payload),
        contentType: 'application/json',
        isFormData: false,
      });
      const newAction: CorrectiveAction = {
        id: `queued-${Date.now()}`,
        description: caDesc.trim(),
        assigned_to: caAssigned.trim() || undefined,
        due_date: caDueDate || undefined,
        status: 'open',
        created_at: new Date().toISOString(),
      };
      const updatedIncident = { ...selected, corrective_actions: [...(selected.corrective_actions || []), newAction] };
      setSelected(updatedIncident);
      setIncidents((prev) => prev.map((i) => i.id === selected.id ? updatedIncident : i));
      setActionMsg('Corrective action queued — will sync when online');
    }

    setCaDesc('');
    setCaAssigned('');
    setCaDueDate('');
    setSaving(false);
    setView('detail');
    setTimeout(() => setActionMsg(''), 3500);
  };

  const updateCAStatus = async (ca: CorrectiveAction, newStatus: string) => {
    if (!selected) return;

    // Optimistic update
    const updatedCAs = (selected.corrective_actions || []).map((c) => c.id === ca.id ? { ...c, status: newStatus } : c);
    const updatedIncident = { ...selected, corrective_actions: updatedCAs };
    setSelected(updatedIncident);
    setIncidents((prev) => prev.map((i) => i.id === selected.id ? updatedIncident : i));

    try {
      if (!online) throw new Error('offline');
      await fetch(`/api/projects/${projectId}/safety/corrective-actions/${ca.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: newStatus }),
      });
    } catch {
      await enqueue({
        url: `/api/projects/${projectId}/safety/corrective-actions/${ca.id}`,
        method: 'PATCH',
        body: JSON.stringify({ status: newStatus }),
        contentType: 'application/json',
        isFormData: false,
      });
    }
  };

  // ─── Advanced Filters & Sorting ─────────────────────────────
  const [showFilterPanel, setShowFilterPanel] = useState(false);
  const [filterDrawerMounted, setFilterDrawerMounted] = useState(false);
  const [sfFilterSeverities, setSfFilterSeverities] = useState<number[]>([]);
  const [sfFilterTypes, setSfFilterTypes] = useState<string[]>([]);
  const [sfFilterStatuses, setSfFilterStatuses] = useState<string[]>([]);
  const [sfFilterAssignedTo, setSfFilterAssignedTo] = useState('');
  const [sfFilterDateFrom, setSfFilterDateFrom] = useState('');
  const [sfFilterDateTo, setSfFilterDateTo] = useState('');
  const [sfSortKey, setSfSortKey] = useState<'date'|'severity'|'status'>('date');
  const [sfSortDir, setSfSortDir] = useState<'asc'|'desc'>('desc');
  const [sfSavedPresets, setSfSavedPresets] = useState<Array<{ name: string; f: Record<string, unknown>; s: string; d: string }>>([]);
  const [sfPresetName, setSfPresetName] = useState('');

  // Drawer open/close with slide animation
  const toggleFilterDrawer = () => {
    if (showFilterPanel) {
      // closing
      setShowFilterPanel(false);
      setTimeout(() => setFilterDrawerMounted(false), 320);
    } else {
      // opening
      setFilterDrawerMounted(true);
      requestAnimationFrame(() => {
        requestAnimationFrame(() => setShowFilterPanel(true));
      });
    }
  };

  useEffect(() => {
    try { const raw = localStorage.getItem(`saguaro_filters_safety_${projectId}`); if (raw) setSfSavedPresets(JSON.parse(raw)); } catch { /* */ }
  }, [projectId]);
  const persistSfPresets = (p: typeof sfSavedPresets) => { setSfSavedPresets(p); try { localStorage.setItem(`saguaro_filters_safety_${projectId}`, JSON.stringify(p)); } catch { /* */ } };
  const saveSfPreset = () => { if (!sfPresetName.trim()) return; persistSfPresets([...sfSavedPresets, { name: sfPresetName.trim(), f: { sev: sfFilterSeverities, tp: sfFilterTypes, st: sfFilterStatuses, at: sfFilterAssignedTo, d1: sfFilterDateFrom, d2: sfFilterDateTo }, s: sfSortKey, d: sfSortDir }]); setSfPresetName(''); };
  const loadSfPreset = (p: typeof sfSavedPresets[0]) => { const f = p.f; setSfFilterSeverities((f.sev as number[]) || []); setSfFilterTypes((f.tp as string[]) || []); setSfFilterStatuses((f.st as string[]) || []); setSfFilterAssignedTo((f.at as string) || ''); setSfFilterDateFrom((f.d1 as string) || ''); setSfFilterDateTo((f.d2 as string) || ''); setSfSortKey((p.s as typeof sfSortKey) || 'date'); setSfSortDir((p.d as typeof sfSortDir) || 'desc'); };
  const deleteSfPreset = (idx: number) => persistSfPresets(sfSavedPresets.filter((_, i) => i !== idx));
  const clearSfFilters = () => { setSfFilterSeverities([]); setSfFilterTypes([]); setSfFilterStatuses([]); setSfFilterAssignedTo(''); setSfFilterDateFrom(''); setSfFilterDateTo(''); setSfSortKey('date'); setSfSortDir('desc'); };
  const toggleSfArr = <T,>(arr: T[], val: T, setter: React.Dispatch<React.SetStateAction<T[]>>) => setter(arr.includes(val) ? arr.filter(v => v !== val) : [...arr, val]);
  const sfActiveFilterCount = [sfFilterSeverities.length > 0, sfFilterTypes.length > 0, sfFilterStatuses.length > 0, !!sfFilterAssignedTo.trim(), !!sfFilterDateFrom || !!sfFilterDateTo].filter(Boolean).length;

  const SEVERITY_LABELS: Record<number, string> = { 1: 'Low', 2: 'Medium', 3: 'High', 4: 'Critical', 5: 'Critical+' };
  const STATUS_OPTIONS = ['Open', 'In Progress', 'Resolved', 'Closed'];

  const getFilteredIncidents = (): Incident[] => {
    let result = [...incidents];
    if (sfFilterSeverities.length > 0) result = result.filter(i => sfFilterSeverities.includes(i.severity));
    if (sfFilterTypes.length > 0) result = result.filter(i => sfFilterTypes.includes(i.type));
    if (sfFilterStatuses.length > 0) result = result.filter(i => sfFilterStatuses.some(fs => fs.toLowerCase().replace(' ', '_') === (i.status || 'open').toLowerCase()));
    if (sfFilterAssignedTo.trim()) {
      const needle = sfFilterAssignedTo.trim().toLowerCase();
      result = result.filter(i =>
        (i.corrective_actions || []).some(ca => (ca.assigned_to || '').toLowerCase().includes(needle))
      );
    }
    if (sfFilterDateFrom || sfFilterDateTo) {
      result = result.filter(i => { if (!i.date) return false; const dt = new Date(i.date).getTime(); if (sfFilterDateFrom && dt < new Date(sfFilterDateFrom).getTime()) return false; if (sfFilterDateTo && dt > new Date(sfFilterDateTo + 'T23:59:59').getTime()) return false; return true; });
    }
    result.sort((a, b) => {
      let cmp = 0;
      if (sfSortKey === 'date') cmp = new Date(a.date || a.created_at || 0).getTime() - new Date(b.date || b.created_at || 0).getTime();
      else if (sfSortKey === 'severity') cmp = (a.severity || 0) - (b.severity || 0);
      else if (sfSortKey === 'status') { const order: Record<string, number> = { open: 0, in_progress: 1, resolved: 2, closed: 3 }; cmp = (order[(a.status||'open')] ?? 1) - (order[(b.status||'open')] ?? 1); }
      return sfSortDir === 'desc' ? -cmp : cmp;
    });
    return result;
  };
  const applySfQuickPreset = (key: string) => {
    clearSfFilters();
    if (key === 'critical') { setSfFilterSeverities([4, 5]); setSfSortKey('severity'); setSfSortDir('desc'); }
    else if (key === 'open') { setSfFilterStatuses(['open']); }
    else if (key === 'my_assignments') { setSfFilterAssignedTo(''); /* user fills in their name */ }
    else if (key === 'this_week') { const d = new Date(); d.setDate(d.getDate() - d.getDay()); setSfFilterDateFrom(d.toISOString().slice(0,10)); }
  };
  const filteredIncidents = getFilteredIncidents();
  const sfChipStyle: React.CSSProperties = { display: 'inline-flex', alignItems: 'center', gap: 4, background: 'rgba(212,160,23,.10)', border: `1px solid rgba(212,160,23,.35)`, borderRadius: 20, padding: '4px 10px', fontSize: 11, fontWeight: 600, color: GOLD, cursor: 'pointer', whiteSpace: 'nowrap' };

  // Stats
  const totalIncidents = incidents.length;
  const openIncidents = incidents.filter((i) => i.status !== 'closed').length;
  const allCAs = incidents.flatMap((i) => i.corrective_actions || []);
  const openCAs = allCAs.filter((ca) => ca.status !== 'closed' && ca.status !== 'verified').length;

  const daysSinceLast = (() => {
    if (incidents.length === 0) return '—';
    const sorted = [...incidents].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    const lastDate = new Date(sorted[0].date);
    const today = new Date();
    const diff = Math.floor((today.getTime() - lastDate.getTime()) / (1000 * 60 * 60 * 24));
    return String(diff);
  })();

  // Severity stars
  const SeverityStars = ({ level, size = 14 }: { level: number; size?: number }) => (
    <span style={{ display: 'inline-flex', gap: 2 }}>
      {[1, 2, 3, 4, 5].map((s) => (
        <svg key={s} viewBox="0 0 24 24" fill={s <= level ? SEVERITY_COLORS[Math.min(level - 1, 4)] : 'none'} stroke={s <= level ? SEVERITY_COLORS[Math.min(level - 1, 4)] : BORDER} strokeWidth={2} width={size} height={size}>
          <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
        </svg>
      ))}
    </span>
  );

  // ─── LIST VIEW ────────────────────────────────────────────────
  if (view === 'list') {
    return (
      <div style={{ padding: '18px 16px' }}>
        <button onClick={() => router.back()} style={backBtn}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round" width={22} height={22}>
            <line x1={19} y1={12} x2={5} y2={12}/><polyline points="12 19 5 12 12 5"/>
          </svg>
        </button>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 }}>
          <div>
            <h1 style={{ margin: '0 0 2px', fontSize: 22, fontWeight: 800, color: TEXT }}>Safety</h1>
            <p style={{ margin: 0, fontSize: 13, color: DIM }}>{projectName}</p>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            {incidents.length > 0 && (
              <button onClick={() => { setSelectMode(!selectMode); setSelectedIds(new Set()); }} style={{
                background: selectMode ? 'rgba(239,68,68,.15)' : 'transparent', border: `1px solid ${selectMode ? RED : BORDER}`,
                borderRadius: 10, padding: '10px 14px', color: selectMode ? RED : DIM, fontSize: 13, fontWeight: 600, cursor: 'pointer',
              }}>
                {selectMode ? 'Cancel' : 'Select'}
              </button>
            )}
            <button onClick={() => { setView('create'); resetCreateForm(); }} style={{
              background: RED, border: 'none', borderRadius: 10, padding: '10px 16px',
              color: '#fff', fontSize: 14, fontWeight: 800, cursor: 'pointer', flexShrink: 0,
            }}>
              + Report
            </button>
          </div>
        </div>

        {selectMode && incidents.length > 0 && (
          <div style={{ display: 'flex', gap: 8, marginBottom: 12, alignItems: 'center' }}>
            <button onClick={selectedIds.size === incidents.length ? deselectAll : selectAll} style={{
              background: 'rgba(239,68,68,.1)', border: `1px solid rgba(239,68,68,.3)`, borderRadius: 8,
              padding: '6px 14px', color: RED, fontSize: 12, fontWeight: 700, cursor: 'pointer',
            }}>
              {selectedIds.size === incidents.length ? 'Deselect All' : 'Select All'}
            </button>
            <span style={{ fontSize: 12, color: DIM }}>{selectedIds.size} selected</span>
          </div>
        )}

        {actionMsg && (
          <div style={{ background: 'rgba(34,197,94,.1)', border: '1px solid rgba(34,197,94,.3)', borderRadius: 10, padding: '12px 14px', marginBottom: 14, color: GREEN, fontSize: 14, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 8 }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}><polyline points="20 6 9 17 4 12"/></svg>{actionMsg}
          </div>
        )}

        {!online && <OfflineBanner />}

        {/* Stat Cards */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 14 }}>
          <StatCard label="Total Incidents" value={String(totalIncidents)} color={TEXT} />
          <StatCard label="Open" value={String(openIncidents)} color={openIncidents > 0 ? RED : GREEN} />
          <StatCard label="Days Since Last" value={daysSinceLast} color={daysSinceLast === '—' ? DIM : parseInt(daysSinceLast) > 30 ? GREEN : AMBER} />
          <StatCard label="Open CAs" value={String(openCAs)} color={openCAs > 0 ? AMBER : GREEN} />
        </div>

        {/* ─── Advanced Filters ─── */}
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 10 }}>
          <button onClick={toggleFilterDrawer} style={{
            background: showFilterPanel || sfActiveFilterCount > 0 ? 'rgba(212,160,23,.12)' : 'transparent',
            border: `1px solid ${showFilterPanel || sfActiveFilterCount > 0 ? GOLD : BORDER}`,
            borderRadius: 10, padding: '8px 14px', color: showFilterPanel || sfActiveFilterCount > 0 ? GOLD : DIM,
            fontSize: 13, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6,
            transition: 'all .2s ease',
          }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/></svg>
            Filters {sfActiveFilterCount > 0 ? `(${sfActiveFilterCount})` : ''}
          </button>
          {sfActiveFilterCount > 0 && (
            <button onClick={clearSfFilters} style={{
              background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 10,
              padding: '8px 12px', color: DIM, fontSize: 12, fontWeight: 600, cursor: 'pointer',
            }}>Clear All</button>
          )}
          {(sfActiveFilterCount > 0 || sfSortKey !== 'date' || sfSortDir !== 'desc') && (
            <span style={{ marginLeft: 'auto', fontSize: 12, color: GOLD, fontWeight: 700, background: 'rgba(212,160,23,.08)', border: `1px solid rgba(212,160,23,.2)`, borderRadius: 8, padding: '4px 10px' }}>
              {filteredIncidents.length} of {incidents.length} shown
            </span>
          )}
          {sfActiveFilterCount === 0 && sfSortKey === 'date' && sfSortDir === 'desc' && (
            <span style={{ marginLeft: 'auto', fontSize: 12, color: DIM, fontWeight: 600 }}>
              {incidents.length} incident{incidents.length !== 1 ? 's' : ''}
            </span>
          )}
        </div>

        {/* Filter Drawer - slides open/closed */}
        {filterDrawerMounted && (
          <div style={{
            background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: 14, marginBottom: 14,
            maxHeight: showFilterPanel ? 900 : 0, overflow: 'hidden', opacity: showFilterPanel ? 1 : 0,
            transition: 'max-height .3s ease, opacity .25s ease, padding .3s ease',
            paddingTop: showFilterPanel ? 14 : 0, paddingBottom: showFilterPanel ? 14 : 0,
          }}>
            {/* Section: Status */}
            <div style={{ marginBottom: 14 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Status</label>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                {STATUS_OPTIONS.map(s => {
                  const key = s.toLowerCase().replace(' ', '_');
                  const active = sfFilterStatuses.includes(key);
                  const statusColor = key === 'open' ? RED : key === 'in_progress' ? AMBER : key === 'resolved' ? BLUE : GREEN;
                  return (
                    <button key={s} onClick={() => toggleSfArr(sfFilterStatuses, key, setSfFilterStatuses)} style={{
                      background: active ? `rgba(${hexRgb(statusColor)},.15)` : 'transparent',
                      border: `1px solid ${active ? statusColor : BORDER}`, borderRadius: 20,
                      padding: '5px 14px', color: active ? statusColor : DIM, fontSize: 12,
                      fontWeight: active ? 700 : 500, cursor: 'pointer', transition: 'all .15s ease',
                    }}>{s}</button>
                  );
                })}
              </div>
            </div>

            {/* Section: Severity */}
            <div style={{ marginBottom: 14 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Severity</label>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                {[1, 2, 3, 4, 5].map(s => {
                  const active = sfFilterSeverities.includes(s);
                  return (
                    <button key={s} onClick={() => toggleSfArr(sfFilterSeverities, s, setSfFilterSeverities)} style={{
                      background: active ? `${SEVERITY_COLORS[s-1]}22` : 'transparent',
                      border: `1px solid ${active ? SEVERITY_COLORS[s-1] : BORDER}`, borderRadius: 20,
                      padding: '5px 12px', color: active ? SEVERITY_COLORS[s-1] : DIM, fontSize: 12,
                      fontWeight: active ? 700 : 500, cursor: 'pointer', transition: 'all .15s ease',
                    }}>{SEVERITY_LABELS[s]} ({s})</button>
                  );
                })}
              </div>
            </div>

            {/* Section: Type/Category */}
            <div style={{ marginBottom: 14 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Type / Category</label>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                {INCIDENT_TYPES.map(t => {
                  const active = sfFilterTypes.includes(t);
                  const tc = TYPE_COLORS[t] || DIM;
                  return (
                    <button key={t} onClick={() => toggleSfArr(sfFilterTypes, t, setSfFilterTypes)} style={{
                      background: active ? `rgba(${hexRgb(tc)},.15)` : 'transparent',
                      border: `1px solid ${active ? tc : BORDER}`, borderRadius: 20,
                      padding: '5px 12px', color: active ? tc : DIM, fontSize: 12,
                      fontWeight: active ? 700 : 500, cursor: 'pointer', whiteSpace: 'nowrap' as const, transition: 'all .15s ease',
                    }}>{TYPE_LABELS[t] || t}</button>
                  );
                })}
              </div>
            </div>

            {/* Section: Assigned To */}
            <div style={{ marginBottom: 14 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Assigned To</label>
              <input
                value={sfFilterAssignedTo}
                onChange={e => setSfFilterAssignedTo(e.target.value)}
                placeholder="Search by assignee name..."
                style={{ ...inp, fontSize: 13, padding: '8px 12px' }}
              />
            </div>

            {/* Section: Date Range */}
            <div style={{ marginBottom: 14 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Date Range</label>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <div style={{ flex: 1 }}>
                  <label style={{ ...lbl, fontSize: 10, marginBottom: 2 }}>From</label>
                  <input type="date" value={sfFilterDateFrom} onChange={e => setSfFilterDateFrom(e.target.value)} style={{ ...inp, fontSize: 12, padding: '7px 8px' }} />
                </div>
                <span style={{ color: DIM, fontSize: 12, marginTop: 14 }}>to</span>
                <div style={{ flex: 1 }}>
                  <label style={{ ...lbl, fontSize: 10, marginBottom: 2 }}>To</label>
                  <input type="date" value={sfFilterDateTo} onChange={e => setSfFilterDateTo(e.target.value)} style={{ ...inp, fontSize: 12, padding: '7px 8px' }} />
                </div>
              </div>
            </div>

            {/* Section: Sort */}
            <div style={{ marginBottom: 14 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Sort By</label>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <select value={sfSortKey} onChange={e => setSfSortKey(e.target.value as typeof sfSortKey)} style={{ ...inp, fontSize: 13, padding: '8px 12px', flex: 1 }}>
                  <option value="date" style={{ background: '#07101C' }}>Date</option>
                  <option value="severity" style={{ background: '#07101C' }}>Severity</option>
                  <option value="status" style={{ background: '#07101C' }}>Status</option>
                </select>
                <button onClick={() => setSfSortDir(d => d === 'asc' ? 'desc' : 'asc')} style={{
                  background: 'rgba(212,160,23,.08)', border: `1px solid rgba(212,160,23,.3)`, borderRadius: 10,
                  padding: '8px 14px', color: GOLD, fontSize: 12, fontWeight: 700, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', gap: 4, whiteSpace: 'nowrap' as const, transition: 'all .15s ease',
                }}>
                  {sfSortDir === 'asc' ? (
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><line x1={12} y1={19} x2={12} y2={5}/><polyline points="5 12 12 5 19 12"/></svg>
                  ) : (
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><line x1={12} y1={5} x2={12} y2={19}/><polyline points="19 12 12 19 5 12"/></svg>
                  )}
                  {sfSortDir === 'asc' ? 'Ascending' : 'Descending'}
                </button>
              </div>
            </div>

            {/* Section: Quick Presets */}
            <div style={{ marginBottom: 14, borderTop: `1px solid ${BORDER}`, paddingTop: 12 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Quick Presets</label>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                <button onClick={() => applySfQuickPreset('open')} style={{
                  ...sfChipStyle, background: 'rgba(239,68,68,.10)', border: '1px solid rgba(239,68,68,.3)', color: RED,
                }}>Open Issues</button>
                <button onClick={() => applySfQuickPreset('critical')} style={{
                  ...sfChipStyle, background: 'rgba(220,38,38,.10)', border: '1px solid rgba(220,38,38,.3)', color: '#DC2626',
                }}>Critical / High</button>
                <button onClick={() => { applySfQuickPreset('my_assignments'); /* Focus the assigned-to input */ }} style={sfChipStyle}>My Assignments</button>
                <button onClick={() => applySfQuickPreset('this_week')} style={{
                  ...sfChipStyle, background: 'rgba(59,130,246,.10)', border: '1px solid rgba(59,130,246,.3)', color: BLUE,
                }}>This Week</button>
              </div>
            </div>

            {/* Section: Save Preset */}
            <div style={{ borderTop: `1px solid ${BORDER}`, paddingTop: 12 }}>
              <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Save Current Filters as Preset</label>
              <div style={{ display: 'flex', gap: 8 }}>
                <input value={sfPresetName} onChange={e => setSfPresetName(e.target.value)} placeholder="Preset name..." style={{ ...inp, fontSize: 12, padding: '7px 10px', flex: 1 }} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); saveSfPreset(); } }} />
                <button onClick={saveSfPreset} disabled={!sfPresetName.trim()} style={{
                  background: sfPresetName.trim() ? GOLD : '#1E3A5F', border: 'none', borderRadius: 8,
                  padding: '7px 16px', color: sfPresetName.trim() ? '#000' : DIM, fontSize: 12, fontWeight: 700,
                  cursor: sfPresetName.trim() ? 'pointer' : 'not-allowed', transition: 'all .15s ease',
                }}>Save</button>
              </div>
            </div>

            {/* Section: Saved Presets */}
            {sfSavedPresets.length > 0 && (
              <div style={{ marginTop: 12 }}>
                <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Saved Presets</label>
                <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                  {sfSavedPresets.map((p, i) => (
                    <span key={i} style={{ ...sfChipStyle, gap: 6 }}>
                      <span onClick={() => loadSfPreset(p)} style={{ cursor: 'pointer' }}>{p.name}</span>
                      <span onClick={() => deleteSfPreset(i)} style={{ cursor: 'pointer', opacity: 0.6, fontSize: 13, lineHeight: 1 }}>&times;</span>
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {sfActiveFilterCount > 0 && (
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 10 }}>
            {sfFilterStatuses.map(s => {
              const statusColor = s === 'open' ? RED : s === 'in_progress' ? AMBER : s === 'resolved' ? BLUE : GREEN;
              return (
                <span key={s} style={{ ...sfChipStyle, background: `rgba(${hexRgb(statusColor)},.12)`, border: `1px solid rgba(${hexRgb(statusColor)},.3)`, color: statusColor }}>
                  {s.replace('_', ' ')} <span onClick={() => setSfFilterStatuses(prev => prev.filter(v => v !== s))} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
                </span>
              );
            })}
            {sfFilterSeverities.map(s => (
              <span key={s} style={{ ...sfChipStyle, background: `${SEVERITY_COLORS[s-1]}18`, border: `1px solid ${SEVERITY_COLORS[s-1]}44`, color: SEVERITY_COLORS[s-1] }}>
                {SEVERITY_LABELS[s]} <span onClick={() => setSfFilterSeverities(prev => prev.filter(v => v !== s))} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            ))}
            {sfFilterTypes.map(t => (
              <span key={t} style={{ ...sfChipStyle, background: `rgba(${hexRgb(TYPE_COLORS[t] || DIM)},.12)`, border: `1px solid rgba(${hexRgb(TYPE_COLORS[t] || DIM)},.3)`, color: TYPE_COLORS[t] || DIM }}>
                {TYPE_LABELS[t] || t} <span onClick={() => setSfFilterTypes(prev => prev.filter(v => v !== t))} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            ))}
            {sfFilterAssignedTo.trim() && (
              <span style={sfChipStyle}>
                Assigned: {sfFilterAssignedTo} <span onClick={() => setSfFilterAssignedTo('')} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            )}
            {(sfFilterDateFrom || sfFilterDateTo) && (
              <span style={{ ...sfChipStyle, background: 'rgba(59,130,246,.10)', border: '1px solid rgba(59,130,246,.3)', color: BLUE }}>
                {sfFilterDateFrom || '...'} - {sfFilterDateTo || '...'} <span onClick={() => { setSfFilterDateFrom(''); setSfFilterDateTo(''); }} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            )}
          </div>
        )}

        {/* List */}
        {loading ? (
          <div style={{ textAlign: 'center', padding: '40px 0', color: DIM }}>Loading incidents...</div>
        ) : incidents.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '40px 16px', color: DIM }}>
            <div style={{ marginBottom: 8, color: GREEN, display: 'flex', justifyContent: 'center', opacity: 0.6 }}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" width={40} height={40}>
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
              </svg>
            </div>
            <p style={{ margin: 0, fontSize: 14 }}>No incidents reported. Tap &quot;+ Report&quot; to log one.</p>
          </div>
        ) : filteredIncidents.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '32px 16px', color: DIM }}>
            <div style={{ marginBottom: 8, display: 'flex', justifyContent: 'center', opacity: 0.5 }}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" width={36} height={36}>
                <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>
              </svg>
            </div>
            <p style={{ margin: '0 0 8px', fontSize: 14, fontWeight: 600 }}>No incidents match your filters</p>
            <button onClick={clearSfFilters} style={{
              background: 'rgba(212,160,23,.12)', border: `1px solid rgba(212,160,23,.3)`, borderRadius: 10,
              padding: '8px 16px', color: GOLD, fontSize: 13, fontWeight: 600, cursor: 'pointer',
            }}>Clear All Filters</button>
          </div>
        ) : (
          <>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {filteredIncidents.map((incident) => {
              const tc = TYPE_COLORS[incident.type] || DIM;
              const isChecked = selectedIds.has(incident.id);
              return (
                <button
                  key={incident.id}
                  onClick={() => selectMode ? toggleSelectId(incident.id) : openDetail(incident)}
                  style={{
                    background: isChecked ? 'rgba(239,68,68,.06)' : RAISED,
                    border: `1px solid ${isChecked ? RED : incident.severity >= 4 ? 'rgba(239,68,68,.3)' : BORDER}`,
                    borderRadius: 14, padding: '14px', textAlign: 'left', width: '100%', cursor: 'pointer',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }}>
                    {selectMode && (
                      <div style={{
                        width: 22, height: 22, borderRadius: 6, border: `2px solid ${isChecked ? RED : BORDER}`,
                        background: isChecked ? RED : 'transparent', display: 'flex', alignItems: 'center',
                        justifyContent: 'center', flexShrink: 0, marginTop: 2,
                      }}>
                        {isChecked && <svg viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth={3} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><polyline points="20 6 9 17 4 12"/></svg>}
                      </div>
                    )}
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                        <span style={{ fontSize: 11, fontWeight: 800, color: DIM }}>{formatDate(incident.date)}</span>
                        <span style={{
                          fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 6,
                          background: `rgba(${hexRgb(tc)},.12)`,
                          color: tc,
                        }}>
                          {TYPE_LABELS[incident.type] || incident.type}
                        </span>
                        {incident.status && incident.status !== 'open' && (
                          <span style={{
                            fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 6,
                            background: `rgba(${hexRgb(incident.status === 'closed' ? GREEN : AMBER)},.12)`,
                            color: incident.status === 'closed' ? GREEN : AMBER,
                          }}>
                            {incident.status}
                          </span>
                        )}
                      </div>
                      <p style={{ margin: '0 0 6px', fontSize: 15, fontWeight: 700, color: TEXT, lineHeight: 1.3 }}>{incident.description}</p>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                        <SeverityStars level={incident.severity} size={12} />
                        {incident.location && (
                          <span style={{ fontSize: 12, color: DIM, display: 'flex', alignItems: 'center', gap: 4 }}>
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={11} height={11}><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0118 0z"/><circle cx={12} cy={10} r={3}/></svg>
                            {incident.location}
                          </span>
                        )}
                        {incident.corrective_actions && incident.corrective_actions.length > 0 && (
                          <span style={{ fontSize: 11, color: DIM }}>{incident.corrective_actions.length} CA{incident.corrective_actions.length !== 1 ? 's' : ''}</span>
                        )}
                      </div>
                    </div>
                    {!selectMode && <span style={{ color: DIM, fontSize: 18, flexShrink: 0, marginTop: 4 }}>›</span>}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Bulk Action Bar */}
          {selectMode && selectedIds.size > 0 && (
            <div style={{
              position: 'fixed', bottom: 0, left: 0, right: 0, background: '#0A1929',
              borderTop: `1px solid ${BORDER}`, padding: '12px 16px', display: 'flex', gap: 8,
              justifyContent: 'center', zIndex: 100,
            }}>
              <button onClick={() => setConfirmDialog({
                title: 'Close Selected Incidents',
                message: `Are you sure you want to close ${selectedIds.size} incident(s)?`,
                action: handleBulkCloseIncidents,
              })} disabled={bulkProcessing} style={{
                background: 'rgba(34,197,94,.15)', border: `1px solid rgba(34,197,94,.3)`, borderRadius: 10,
                padding: '10px 14px', color: GREEN, fontSize: 12, fontWeight: 700, cursor: 'pointer', flex: 1,
              }}>
                Close ({selectedIds.size})
              </button>
              <button onClick={() => setShowBulkCA(true)} disabled={bulkProcessing} style={{
                background: 'rgba(212,160,23,.15)', border: `1px solid rgba(212,160,23,.3)`, borderRadius: 10,
                padding: '10px 14px', color: GOLD, fontSize: 12, fontWeight: 700, cursor: 'pointer', flex: 1,
              }}>
                Assign CA ({selectedIds.size})
              </button>
              <button onClick={() => handleBulkExportIncidents()} disabled={bulkProcessing} style={{
                background: 'rgba(59,130,246,.15)', border: `1px solid rgba(59,130,246,.3)`, borderRadius: 10,
                padding: '10px 14px', color: BLUE, fontSize: 12, fontWeight: 700, cursor: 'pointer', flex: 1,
              }}>
                Export ({selectedIds.size})
              </button>
            </div>
          )}

          {/* Bulk Corrective Action Modal */}
          {showBulkCA && (
            <div style={{
              position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,.12)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200, padding: 20,
            }}>
              <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 16, padding: 24, width: '100%', maxWidth: 400 }}>
                <h3 style={{ margin: '0 0 14px', fontSize: 18, fontWeight: 800, color: TEXT }}>Assign Corrective Action to {selectedIds.size} Incident(s)</h3>
                <div style={{ marginBottom: 10 }}>
                  <label style={lbl}>Description *</label>
                  <textarea value={bulkCADesc} onChange={(e) => setBulkCADesc(e.target.value)} placeholder="Describe the corrective action..." rows={3} style={inp} required />
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 10 }}>
                  <div>
                    <label style={lbl}>Assigned To</label>
                    <input value={bulkCAAssigned} onChange={(e) => setBulkCAAssigned(e.target.value)} placeholder="Person responsible" style={inp} />
                  </div>
                  <div>
                    <label style={lbl}>Due Date</label>
                    <input type="date" value={bulkCADueDate} onChange={(e) => setBulkCADueDate(e.target.value)} style={inp} />
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 10 }}>
                  <button onClick={() => { setShowBulkCA(false); setBulkCADesc(''); setBulkCAAssigned(''); setBulkCADueDate(''); }} style={{
                    flex: 1, background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 10,
                    padding: '12px', color: DIM, fontSize: 14, cursor: 'pointer',
                  }}>Cancel</button>
                  <button onClick={handleBulkAssignCA} disabled={bulkProcessing || !bulkCADesc.trim()} style={{
                    flex: 1, background: bulkProcessing ? '#1E3A5F' : GOLD, border: 'none', borderRadius: 10,
                    padding: '12px', color: bulkProcessing ? DIM : '#000', fontSize: 14, fontWeight: 700, cursor: bulkProcessing ? 'wait' : 'pointer',
                  }}>{bulkProcessing ? 'Assigning...' : 'Assign CA'}</button>
                </div>
              </div>
            </div>
          )}

          {/* Confirmation Dialog */}
          {confirmDialog && (
            <div style={{
              position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,.12)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200, padding: 20,
            }}>
              <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 16, padding: 24, width: '100%', maxWidth: 400 }}>
                <h3 style={{ margin: '0 0 8px', fontSize: 18, fontWeight: 800, color: TEXT }}>{confirmDialog.title}</h3>
                <p style={{ margin: '0 0 20px', fontSize: 14, color: DIM, lineHeight: 1.5 }}>{confirmDialog.message}</p>
                <div style={{ display: 'flex', gap: 10 }}>
                  <button onClick={() => setConfirmDialog(null)} style={{
                    flex: 1, background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 10,
                    padding: '12px', color: DIM, fontSize: 14, cursor: 'pointer',
                  }}>Cancel</button>
                  <button onClick={() => { confirmDialog.action(); setConfirmDialog(null); }} disabled={bulkProcessing} style={{
                    flex: 1, background: RED, border: 'none', borderRadius: 10,
                    padding: '12px', color: '#fff', fontSize: 14, fontWeight: 700, cursor: 'pointer',
                  }}>{bulkProcessing ? 'Processing...' : 'Confirm'}</button>
                </div>
              </div>
            </div>
          )}
          </>
        )}
      </div>
    );
  }

  // ─── DETAIL VIEW ──────────────────────────────────────────────
  if (view === 'detail' && selected) {
    const tc = TYPE_COLORS[selected.type] || DIM;
    return (
      <div style={{ padding: '18px 16px' }}>
        <button onClick={() => { setView('list'); setActionMsg(''); }} style={backBtn}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round" width={22} height={22}>
            <line x1={19} y1={12} x2={5} y2={12}/><polyline points="12 19 5 12 12 5"/>
          </svg>
        </button>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
          <span style={{ fontSize: 12, fontWeight: 800, color: DIM }}>{formatDate(selected.date)}</span>
          <span style={{
            fontSize: 12, fontWeight: 700, padding: '3px 10px', borderRadius: 6,
            background: `rgba(${hexRgb(tc)},.12)`,
            color: tc,
          }}>
            {TYPE_LABELS[selected.type] || selected.type}
          </span>
          {selected.status && (
            <span style={{
              fontSize: 12, fontWeight: 700, padding: '3px 10px', borderRadius: 6,
              background: `rgba(${hexRgb(selected.status === 'closed' ? GREEN : AMBER)},.12)`,
              color: selected.status === 'closed' ? GREEN : AMBER,
            }}>
              {selected.status}
            </span>
          )}
        </div>

        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }}>
          <h1 style={{ margin: '0 0 6px', fontSize: 20, fontWeight: 800, color: TEXT, lineHeight: 1.3, flex: 1 }}>{selected.description}</h1>
          <button onClick={() => {
            const inc = selected;
            const casHtml = (inc.corrective_actions || []).map(ca =>
              `<tr><td>${ca.description}</td><td>${ca.assigned_to || '—'}</td><td>${formatDate(ca.due_date)}</td><td><span class="badge">${CA_STATUS_LABELS[ca.status] || ca.status}</span></td></tr>`
            ).join('');
            const photosHtml = (inc.photo_urls || []).map(url =>
              `<img src="${url}" alt="Incident photo" />`
            ).join('');
            exportPDF(`Safety Incident - ${formatDate(inc.date)}`, `
              <h1>Safety Incident Report</h1>
              <table>
                <tr><th>Date</th><td>${formatDate(inc.date)}</td></tr>
                <tr><th>Type</th><td>${TYPE_LABELS[inc.type] || inc.type}</td></tr>
                <tr><th>Severity</th><td>${inc.severity}/5</td></tr>
                <tr><th>Location</th><td>${inc.location || '—'}</td></tr>
                <tr><th>Status</th><td><span class="badge">${inc.status || 'open'}</span></td></tr>
              </table>
              <h2>Description</h2>
              <div class="section"><p>${(inc.description || '').replace(/\n/g, '<br/>')}</p></div>
              ${(inc.corrective_actions || []).length > 0 ? `
                <h2>Corrective Actions (${inc.corrective_actions!.length})</h2>
                <table><tr><th>Description</th><th>Assigned To</th><th>Due Date</th><th>Status</th></tr>${casHtml}</table>
              ` : ''}
              ${photosHtml ? `<h2>Photos</h2>${photosHtml}` : ''}
            `);
          }} style={{
            background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 10,
            padding: '8px 14px', color: DIM, fontSize: 13, fontWeight: 600, cursor: 'pointer',
            display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0,
          }}>
            <PdfIcon /> Export PDF
          </button>
          <button onClick={() => setShowEmail(true)} style={{
            background: 'rgba(212,160,23,.1)', border: '1px solid rgba(212,160,23,.3)', borderRadius: 10,
            padding: '8px 14px', color: GOLD, fontSize: 13, fontWeight: 600, cursor: 'pointer',
            display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0,
          }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}>
              <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/>
            </svg>
            Email Report
          </button>
        </div>

        {showEmail && (
          <EmailComposer
            projectId={projectId}
            onClose={() => setShowEmail(false)}
            onSent={() => { setShowEmail(false); setActionMsg('Email sent successfully'); setTimeout(() => setActionMsg(''), 3500); }}
            defaultSubject={`Safety Incident Report - ${TYPE_LABELS[selected.type] || selected.type} - ${formatDate(selected.date)}`}
            defaultBody={[
              `Safety Incident Report`,
              `Date: ${formatDate(selected.date)}`,
              `Type: ${TYPE_LABELS[selected.type] || selected.type}`,
              `Severity: ${selected.severity}/5`,
              selected.location ? `Location: ${selected.location}` : '',
              `Status: ${selected.status || 'open'}`,
              '',
              'Description:',
              selected.description,
              '',
              ...((selected.corrective_actions || []).length > 0
                ? ['Corrective Actions:', ...(selected.corrective_actions || []).map(ca =>
                    `- ${ca.description}${ca.assigned_to ? ` (Assigned: ${ca.assigned_to})` : ''}${ca.due_date ? ` Due: ${formatDate(ca.due_date)}` : ''} [${CA_STATUS_LABELS[ca.status] || ca.status}]`
                  )]
                : []),
            ].filter(Boolean).join('\n')}
            module="safety"
            itemId={selected.id}
            itemTitle={selected.description.slice(0, 60)}
          />
        )}

        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
          <SeverityStars level={selected.severity} />
          <span style={{ fontSize: 13, color: DIM }}>Severity {selected.severity}/5</span>
        </div>

        {actionMsg && (
          <div style={{ background: 'rgba(34,197,94,.1)', border: '1px solid rgba(34,197,94,.3)', borderRadius: 10, padding: '12px 14px', marginBottom: 14, color: GREEN, fontSize: 14, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 8 }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}><polyline points="20 6 9 17 4 12"/></svg>{actionMsg}
          </div>
        )}

        {!online && <OfflineBanner />}

        {/* Incident Details */}
        <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px', marginBottom: 14 }}>
          <p style={secLbl}>Incident Details</p>
          {selected.location && (
            <p style={{ margin: '0 0 8px', fontSize: 14, color: TEXT, display: 'flex', alignItems: 'center', gap: 6 }}>
              <svg viewBox="0 0 24 24" fill="none" stroke={DIM} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0118 0z"/><circle cx={12} cy={10} r={3}/></svg>
              {selected.location}
            </p>
          )}
          <p style={{ margin: 0, fontSize: 14, color: TEXT, lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{selected.description}</p>
        </div>

        {/* Attached photos */}
        {selected.photo_urls && selected.photo_urls.length > 0 && (
          <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px', marginBottom: 14 }}>
            <p style={secLbl}>Photos</p>
            <div style={{ display: 'flex', gap: 8, overflowX: 'auto' }}>
              {selected.photo_urls.map((url, i) => (
                // eslint-disable-next-line @next/next/no-img-element
                <img key={i} src={url} alt={`Photo ${i + 1}`} style={{ width: 100, height: 100, objectFit: 'cover', borderRadius: 10, border: `1px solid ${BORDER}`, flexShrink: 0 }} />
              ))}
            </div>
          </div>
        )}

        {/* Corrective Actions */}
        <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px', marginBottom: 14 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
            <p style={{ ...secLbl, margin: 0 }}>Corrective Actions ({(selected.corrective_actions || []).length})</p>
            <button
              onClick={() => { setView('add_ca'); setCaDesc(''); setCaAssigned(''); setCaDueDate(''); }}
              style={{ background: 'rgba(212,160,23,.12)', border: `1px solid rgba(212,160,23,.3)`, borderRadius: 8, padding: '5px 12px', color: GOLD, fontSize: 12, fontWeight: 700, cursor: 'pointer' }}
            >
              + Add CA
            </button>
          </div>
          {(!selected.corrective_actions || selected.corrective_actions.length === 0) ? (
            <p style={{ margin: 0, fontSize: 13, color: DIM, fontStyle: 'italic' }}>No corrective actions yet</p>
          ) : (
            selected.corrective_actions.map((ca, i) => {
              const caColor = CA_STATUS_COLORS[ca.status] || DIM;
              const currentIdx = CA_STATUSES.indexOf(ca.status);
              const nextStatus = currentIdx < CA_STATUSES.length - 1 ? CA_STATUSES[currentIdx + 1] : null;
              return (
                <div key={ca.id} style={{ padding: '12px 0', borderTop: i > 0 ? `1px solid ${BORDER}` : 'none' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                    <span style={{
                      fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 6,
                      background: `rgba(${hexRgb(caColor)},.12)`,
                      color: caColor,
                    }}>
                      {CA_STATUS_LABELS[ca.status] || ca.status}
                    </span>
                    {ca.due_date && <span style={{ fontSize: 11, color: new Date(ca.due_date) < new Date() && ca.status !== 'closed' && ca.status !== 'verified' ? RED : DIM }}>Due {formatDate(ca.due_date)}</span>}
                  </div>
                  <p style={{ margin: '4px 0', fontSize: 14, color: TEXT, lineHeight: 1.4 }}>{ca.description}</p>
                  {ca.assigned_to && <p style={{ margin: '2px 0 0', fontSize: 12, color: DIM }}>Assigned to: {ca.assigned_to}</p>}
                  {nextStatus && (
                    <button
                      onClick={() => updateCAStatus(ca, nextStatus)}
                      style={{
                        marginTop: 8, background: `rgba(${hexRgb(CA_STATUS_COLORS[nextStatus])},.12)`,
                        border: `1px solid rgba(${hexRgb(CA_STATUS_COLORS[nextStatus])},.3)`,
                        borderRadius: 8, padding: '6px 14px',
                        color: CA_STATUS_COLORS[nextStatus], fontSize: 12, fontWeight: 700, cursor: 'pointer',
                      }}
                    >
                      Move to {CA_STATUS_LABELS[nextStatus]}
                    </button>
                  )}
                </div>
              );
            })
          )}
        </div>
      </div>
    );
  }

  // ─── ADD CORRECTIVE ACTION VIEW ───────────────────────────────
  if (view === 'add_ca' && selected) {
    return (
      <div style={{ padding: '18px 16px' }}>
        <button onClick={() => setView('detail')} style={backBtn}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round" width={22} height={22}>
            <line x1={19} y1={12} x2={5} y2={12}/><polyline points="12 19 5 12 12 5"/>
          </svg>
        </button>
        <h1 style={{ margin: '0 0 2px', fontSize: 22, fontWeight: 800, color: GOLD }}>Add Corrective Action</h1>
        <p style={{ margin: '0 0 18px', fontSize: 13, color: DIM }}>For: {selected.description.slice(0, 60)}{selected.description.length > 60 ? '...' : ''}</p>

        {!online && <OfflineBanner />}

        <form onSubmit={handleAddCA}>
          <div style={card}>
            <p style={secLbl}>Corrective Action Details</p>

            <div style={{ marginBottom: 10 }}>
              <label style={lbl}>Description *</label>
              <textarea value={caDesc} onChange={(e) => setCaDesc(e.target.value)} placeholder="Describe the corrective action to be taken..." rows={4} style={inp} required />
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 10 }}>
              <div>
                <label style={lbl}>Assigned To</label>
                <input value={caAssigned} onChange={(e) => setCaAssigned(e.target.value)} placeholder="Person responsible" style={inp} />
              </div>
              <div>
                <label style={lbl}>Due Date</label>
                <input type="date" value={caDueDate} onChange={(e) => setCaDueDate(e.target.value)} style={inp} />
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', gap: 10 }}>
            <button type="button" onClick={() => setView('detail')} style={{ flex: 1, background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 12, padding: '16px', color: DIM, fontSize: 15, cursor: 'pointer' }}>
              Cancel
            </button>
            <button type="submit" disabled={saving} style={{ flex: 2, background: saving ? '#1E3A5F' : GOLD, border: 'none', borderRadius: 12, padding: '16px', color: saving ? DIM : '#000', fontSize: 15, fontWeight: 800, cursor: saving ? 'wait' : 'pointer' }}>
              {saving ? 'Saving...' : 'Add Corrective Action'}
            </button>
          </div>
        </form>
      </div>
    );
  }

  // ─── CREATE INCIDENT VIEW ─────────────────────────────────────
  return (
    <div style={{ padding: '18px 16px' }}>
      <button onClick={() => setView('list')} style={backBtn}>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round" width={22} height={22}>
          <line x1={19} y1={12} x2={5} y2={12}/><polyline points="12 19 5 12 12 5"/>
        </svg>
      </button>
      <h1 style={{ margin: '0 0 2px', fontSize: 22, fontWeight: 800, color: RED }}>Report Incident</h1>
      <p style={{ margin: '0 0 18px', fontSize: 13, color: DIM }}>Log a safety incident for this project</p>

      {!online && <OfflineBanner />}

      <form onSubmit={handleCreateIncident}>
        <div style={card}>
          <p style={secLbl}>Incident Information</p>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 10 }}>
            <div>
              <label style={lbl}>Date *</label>
              <input type="date" value={newDate} onChange={(e) => setNewDate(e.target.value)} style={inp} required />
            </div>
            <div>
              <label style={lbl}>Type *</label>
              <select value={newType} onChange={(e) => setNewType(e.target.value)} style={inp}>
                {INCIDENT_TYPES.map((t) => <option key={t} value={t} style={{ background: '#0D1D2E' }}>{TYPE_LABELS[t]}</option>)}
              </select>
            </div>
          </div>

          <div style={{ marginBottom: 10 }}>
            <label style={lbl}>Description *</label>
            <textarea value={newDesc} onChange={(e) => setNewDesc(e.target.value)} placeholder="Describe what happened, who was involved, contributing factors..." rows={4} style={inp} required />
          </div>

          <div style={{ marginBottom: 10 }}>
            <label style={lbl}>Location</label>
            <input value={newLocation} onChange={(e) => setNewLocation(e.target.value)} placeholder="e.g. Level 3, South stairwell" style={inp} />
          </div>

          <div style={{ marginBottom: 10 }}>
            <label style={lbl}>Severity (1-5) *</label>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 4 }}>
              <input
                type="range"
                min={1}
                max={5}
                step={1}
                value={newSeverity}
                onChange={(e) => setNewSeverity(parseInt(e.target.value))}
                style={{ flex: 1, accentColor: SEVERITY_COLORS[Math.min(newSeverity - 1, 4)] }}
              />
              <SeverityStars level={newSeverity} />
              <span style={{ fontSize: 14, fontWeight: 800, color: SEVERITY_COLORS[Math.min(newSeverity - 1, 4)], minWidth: 16, textAlign: 'center' }}>{newSeverity}</span>
            </div>
          </div>
        </div>

        <div style={card}>
          <p style={secLbl}>Corrective Action</p>
          <div style={{ marginBottom: 10 }}>
            <label style={lbl}>Initial Corrective Action</label>
            <textarea value={newCA} onChange={(e) => setNewCA(e.target.value)} placeholder="Describe immediate corrective measures taken or needed..." rows={3} style={inp} />
          </div>
        </div>

        {/* Photo attachment */}
        <div style={card}>
          <p style={secLbl}>Photos</p>
          <input ref={photoRef} type="file" accept="image/*" capture="environment" multiple onChange={handlePhotoCapture} style={{ display: 'none' }} />
          <button type="button" onClick={() => photoRef.current?.click()} style={{ width: '100%', background: 'transparent', border: `2px dashed rgba(212,160,23,.4)`, borderRadius: 10, padding: '14px', color: GOLD, fontSize: 14, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: photoPreviews.length ? 10 : 0 }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round" width={20} height={20}><path d="M23 19a2 2 0 01-2 2H3a2 2 0 01-2-2V8a2 2 0 012-2h4l2-3h6l2 3h4a2 2 0 012 2z"/><circle cx={12} cy={13} r={4}/></svg>
            Attach Photo
          </button>
          {photoPreviews.length > 0 && (
            <div style={{ display: 'flex', gap: 8, overflowX: 'auto', paddingBottom: 4 }}>
              {photoPreviews.map((src, i) => (
                <div key={i} style={{ position: 'relative', flexShrink: 0 }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={src} alt={`Photo ${i + 1}`} style={{ width: 72, height: 72, objectFit: 'cover', borderRadius: 8, border: `1px solid ${BORDER}` }} />
                  <button type="button" onClick={() => removePhoto(i)} style={{ position: 'absolute', top: -6, right: -6, width: 20, height: 20, borderRadius: '50%', background: RED, border: 'none', color: '#fff', fontSize: 12, fontWeight: 900, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>x</button>
                </div>
              ))}
            </div>
          )}
        </div>

        <div style={{ display: 'flex', gap: 10 }}>
          <button type="button" onClick={() => { setView('list'); resetCreateForm(); }} style={{ flex: 1, background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 12, padding: '16px', color: DIM, fontSize: 15, cursor: 'pointer' }}>
            Cancel
          </button>
          <button type="submit" disabled={saving} style={{ flex: 2, background: saving ? '#1E3A5F' : RED, border: 'none', borderRadius: 12, padding: '16px', color: saving ? DIM : '#fff', fontSize: 15, fontWeight: 800, cursor: saving ? 'wait' : 'pointer' }}>
            {saving ? 'Saving...' : online ? 'Report Incident' : 'Report (Offline — will sync)'}
          </button>
        </div>
      </form>
    </div>
  );
}

export default function FieldSafetyPage() {
  return (
    <Suspense fallback={<div style={{ padding: 32, color: '#8BAAC8', textAlign: 'center' }}>Loading...</div>}>
      <SafetyPage />
    </Suspense>
  );
}

// Shared helpers
function StatCard({ label, value, color }: { label: string; value: string; color: string }) {
  return (
    <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 12, padding: '12px 14px' }}>
      <p style={{ margin: 0, fontSize: 11, fontWeight: 700, color: DIM, textTransform: 'uppercase', letterSpacing: 0.5 }}>{label}</p>
      <p style={{ margin: '4px 0 0', fontSize: 20, fontWeight: 800, color }}>{value}</p>
    </div>
  );
}

function OfflineBanner() {
  return <div style={{ background: 'rgba(239,68,68,.1)', border: '1px solid rgba(239,68,68,.25)', borderRadius: 8, padding: '8px 12px', marginBottom: 12, fontSize: 13, color: RED, fontWeight: 600 }}>Offline — will sync when reconnected</div>;
}

const card: React.CSSProperties = { background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px 14px 6px', marginBottom: 12 };
const secLbl: React.CSSProperties = { margin: '0 0 10px', fontSize: 11, fontWeight: 700, color: DIM, textTransform: 'uppercase', letterSpacing: 0.8 };
const lbl: React.CSSProperties = { display: 'block', fontSize: 12, color: DIM, marginBottom: 4, fontWeight: 600 };
const inp: React.CSSProperties = { width: '100%', background: '#07101C', border: '1px solid #1E3A5F', borderRadius: 10, padding: '11px 14px', color: '#F0F4FF', fontSize: 15, outline: 'none' };
const backBtn: React.CSSProperties = { background: 'none', border: 'none', color: DIM, cursor: 'pointer', padding: '8px', marginLeft: -8, display: 'flex', alignItems: 'center', marginBottom: 4 };

function hexRgb(hex: string): string {
  const r = parseInt((hex || '#888').slice(1, 3), 16);
  const g = parseInt((hex || '#888').slice(3, 5), 16);
  const b = parseInt((hex || '#888').slice(5, 7), 16);
  return `${r},${g},${b}`;
}
