-- ============================================================
-- Saguaro CRM — Official Construction Document System
-- Migration: 20260308_documents.sql
-- Run AFTER: 20260308_foundation.sql, 20260308_core_modules.sql
-- ============================================================
-- Every real legal document generated by the AI bot.
-- AIA forms, lien waivers, pay applications, bid documents,
-- closeout packages — all auto-generated, tracked, and signed.
-- ============================================================

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

-- ────────────────────────────────────────────────────────────
-- DOCUMENT TEMPLATES  (master library of form templates)
-- ────────────────────────────────────────────────────────────
create table if not exists public.document_templates (
  id            uuid    primary key default gen_random_uuid(),
  template_code text    not null unique,
  -- e.g. 'AIA_G702', 'AIA_G703', 'AIA_G704', 'AIA_G706',
  --      'AIA_A310_BID_BOND', 'AIA_A312_PERF_BOND', 'AIA_A312_PAY_BOND',
  --      'LIEN_WAIVER_COND_PARTIAL', 'LIEN_WAIVER_UNCOND_FINAL',
  --      'PRELIMINARY_NOTICE', 'WH347_CERTIFIED_PAYROLL',
  --      'NON_COLLUSION_AFFIDAVIT', 'W9', 'ACORD_25', 'CLOSEOUT_CHECKLIST'
  name          text    not null,
  category      text    not null
    check (category in ('pay_application','lien_waiver','bond','insurance','bid_document',
                        'closeout','payroll','government','subcontract','general')),
  description   text,
  -- Template content (HTML with {{placeholder}} fields)
  template_html text    not null,
  -- JSON schema of fields this template requires
  fields_schema jsonb   not null default '[]',
  -- Which states this applies to (null = federal/all states)
  applicable_states text[],
  -- Which project types require this document
  required_for  jsonb   not null default '[]',
  -- Is this legally required or recommended
  is_mandatory  boolean not null default false,
  sort_order    integer not null default 0,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

create index if not exists idx_doc_templates_category on public.document_templates (category, is_active);
create index if not exists idx_doc_templates_code     on public.document_templates (template_code);

-- ────────────────────────────────────────────────────────────
-- PROJECT DOCUMENTS  (every generated document per project)
-- ────────────────────────────────────────────────────────────
create table if not exists public.project_documents (
  id              uuid    primary key default gen_random_uuid(),
  tenant_id       uuid    not null,
  project_id      uuid    not null references public.projects(id) on delete cascade,
  template_code   text    references public.document_templates(template_code) on delete set null,
  -- What entity this document is attached to
  entity_type     text    check (entity_type in ('project','contract','invoice','rfi','change_order','bid_package','safety_incident','inspection','punch_list','subcontractor')),
  entity_id       uuid,
  -- Document metadata
  document_type   text    not null,  -- e.g. 'AIA G702', 'Conditional Lien Waiver'
  document_number text,              -- sequential: PAY-001, LW-2026-004
  title           text    not null,
  description     text,
  -- Content
  content_html    text,              -- AI-generated HTML document
  content_pdf_url text,              -- Supabase Storage path to PDF version
  -- Field values (JSON map of all filled fields)
  field_values    jsonb   not null default '{}',
  -- AI generation metadata
  ai_generated    boolean not null default false,
  ai_model        text,
  ai_generated_at timestamptz,
  ai_confidence   text    check (ai_confidence in ('high','medium','low')),
  ai_flags        jsonb   not null default '[]',  -- issues flagged by AI during generation
  -- Status workflow
  status          text    not null default 'draft'
    check (status in ('draft','ai_review','ready','sent','signed','voided','superseded')),
  -- Signature tracking
  requires_signature    boolean not null default false,
  signatory_name        text,
  signatory_email       text,
  signature_requested_at timestamptz,
  signed_at             timestamptz,
  signature_url         text,   -- DocuSign / HelloSign envelope URL
  -- Period
  period_start    date,
  period_end      date,
  -- Financial (for pay apps, lien waivers)
  gross_amount    numeric(14,2),
  retainage_amount numeric(14,2),
  net_amount      numeric(14,2),
  -- Misc
  notes           text,
  created_by      uuid,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_project_documents_project  on public.project_documents (tenant_id, project_id, document_type, created_at desc);
create index if not exists idx_project_documents_entity   on public.project_documents (entity_type, entity_id);
create index if not exists idx_project_documents_status   on public.project_documents (status, requires_signature);

-- ────────────────────────────────────────────────────────────
-- PAY APPLICATIONS  (AIA G702/G703 data model)
-- ────────────────────────────────────────────────────────────
create table if not exists public.pay_applications (
  id                  uuid    primary key default gen_random_uuid(),
  tenant_id           uuid    not null,
  project_id          uuid    not null references public.projects(id) on delete cascade,
  contract_id         uuid    references public.contracts(id) on delete set null,
  document_id         uuid    references public.project_documents(id) on delete set null,
  -- AIA G702 fields
  application_number  integer not null,  -- sequential: 1, 2, 3...
  period_from         date    not null,
  period_to           date    not null,
  -- Contract summary
  contract_sum        numeric(14,2) not null default 0,
  net_change_orders   numeric(14,2) not null default 0,
  contract_sum_to_date numeric(14,2) generated always as (contract_sum + net_change_orders) stored,
  -- Work complete
  total_completed_and_stored numeric(14,2) not null default 0,
  pct_complete        numeric(5,2)  generated always as
    (case when contract_sum + net_change_orders > 0
          then 100.0 * total_completed_and_stored / (contract_sum + net_change_orders)
          else 0 end) stored,
  -- Retainage
  retainage_pct       numeric(5,2) not null default 10,
  retainage_held      numeric(14,2) not null default 0,
  -- Previous payments
  total_previous_payments numeric(14,2) not null default 0,
  -- Current application
  current_payment_due numeric(14,2) generated always as
    (total_completed_and_stored - retainage_held - total_previous_payments) stored,
  -- Balance
  balance_to_finish   numeric(14,2) generated always as
    (contract_sum + net_change_orders - total_completed_and_stored) stored,
  -- Status
  status              text    not null default 'draft'
    check (status in ('draft','submitted','certified','approved','paid','rejected','void')),
  submitted_at        timestamptz,
  certified_at        timestamptz,
  certified_by        text,
  paid_at             timestamptz,
  -- Lien waiver
  conditional_lien_waiver_id   uuid references public.project_documents(id) on delete set null,
  unconditional_lien_waiver_id uuid references public.project_documents(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_pay_apps_project  on public.pay_applications (project_id, application_number desc);
create index if not exists idx_pay_apps_contract on public.pay_applications (contract_id, status);

-- ────────────────────────────────────────────────────────────
-- SCHEDULE OF VALUES  (AIA G703 — line items for each pay app)
-- ────────────────────────────────────────────────────────────
create table if not exists public.schedule_of_values (
  id                  uuid    primary key default gen_random_uuid(),
  pay_application_id  uuid    not null references public.pay_applications(id) on delete cascade,
  contract_id         uuid    not null,
  -- AIA G703 columns
  item_number         text    not null,   -- A, B, C or 01, 02, 03
  description         text    not null,
  scheduled_value     numeric(14,2) not null default 0,
  -- From previous applications
  pct_complete_prev   numeric(5,2)  not null default 0,
  work_complete_prev  numeric(14,2) not null default 0,
  -- This period
  pct_complete_this   numeric(5,2)  not null default 0,
  work_complete_this  numeric(14,2) not null default 0,
  -- Materials stored
  materials_stored    numeric(14,2) not null default 0,
  -- Totals (computed)
  total_complete_and_stored numeric(14,2) generated always as
    (work_complete_prev + work_complete_this + materials_stored) stored,
  pct_complete_total  numeric(5,2)  generated always as
    (case when scheduled_value > 0
          then 100.0 * (work_complete_prev + work_complete_this + materials_stored) / scheduled_value
          else 0 end) stored,
  balance_to_finish   numeric(14,2) generated always as
    (scheduled_value - work_complete_prev - work_complete_this - materials_stored) stored,
  retainage           numeric(14,2) not null default 0,
  sort_order          integer not null default 0,
  created_at          timestamptz not null default now()
);

create index if not exists idx_sov_pay_app on public.schedule_of_values (pay_application_id, sort_order);

-- ────────────────────────────────────────────────────────────
-- LIEN WAIVERS  (conditional + unconditional, partial + final)
-- ────────────────────────────────────────────────────────────
create table if not exists public.lien_waivers (
  id                  uuid    primary key default gen_random_uuid(),
  tenant_id           uuid    not null,
  project_id          uuid    not null references public.projects(id) on delete cascade,
  contract_id         uuid    references public.contracts(id) on delete set null,
  pay_application_id  uuid    references public.pay_applications(id) on delete set null,
  document_id         uuid    references public.project_documents(id) on delete set null,
  -- Waiver classification
  waiver_type         text    not null
    check (waiver_type in (
      'conditional_partial',    -- Claimant received payment contingent on clearing
      'unconditional_partial',  -- Claimant received and cleared payment (partial)
      'conditional_final',      -- Final payment pending
      'unconditional_final'     -- All amounts received, final waiver
    )),
  -- State (determines statutory form)
  state               text    not null,   -- 'AZ', 'CA', 'TX', 'NV', 'NM', 'FL', etc.
  -- Parties
  claimant_name       text    not null,   -- Sub or supplier giving the waiver
  claimant_address    text,
  claimant_license    text,
  owner_name          text,
  gc_name             text,
  -- Project
  project_address     text,
  -- Amounts
  through_date        date,               -- "through [date]" — the period covered
  amount              numeric(14,2) not null,   -- amount being waived
  exceptions          text,               -- "EXCEPT: unpaid invoices for..."
  -- Status
  status              text    not null default 'draft'
    check (status in ('draft','sent','signed','voided')),
  sent_at             timestamptz,
  signed_at           timestamptz,
  signer_name         text,
  signer_title        text,
  notarized           boolean not null default false,
  notarized_at        timestamptz,
  -- Notary (some states require)
  notary_name         text,
  notary_commission   text,
  -- AI generation
  ai_generated        boolean not null default false,
  statutory_compliant boolean not null default true,  -- using the correct statutory form
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists idx_lien_waivers_project  on public.lien_waivers (project_id, waiver_type, status);
create index if not exists idx_lien_waivers_contract on public.lien_waivers (contract_id, signed_at desc);

-- ────────────────────────────────────────────────────────────
-- BID DOCUMENTS  (all documents in the bid folder per package)
-- ────────────────────────────────────────────────────────────
create table if not exists public.bid_documents (
  id              uuid    primary key default gen_random_uuid(),
  tenant_id       uuid    not null,
  bid_package_id  uuid    not null references public.bid_packages(id) on delete cascade,
  document_type   text    not null
    check (document_type in (
      'instructions_to_bidders',
      'bid_form',
      'bid_bond',
      'non_collusion_affidavit',
      'subcontractor_list',
      'insurance_requirements',
      'prevailing_wage_determination',
      'eeo_requirements',
      'mwbe_requirements',
      'project_schedule',
      'reference_requirements',
      'general_conditions_summary',
      'addendum',
      'other'
    )),
  document_number text,   -- e.g. 'ADD-001' for addenda
  title           text    not null,
  content_html    text,   -- AI-generated content
  file_url        text,   -- Supabase Storage URL if uploaded
  version         text    not null default '1',
  ai_generated    boolean not null default false,
  status          text    not null default 'draft'
    check (status in ('draft','issued','superseded')),
  issued_at       timestamptz,
  created_by      uuid,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_bid_documents_package on public.bid_documents (bid_package_id, document_type, status);

-- ────────────────────────────────────────────────────────────
-- CLOSEOUT PACKAGES  (final project completion documentation)
-- ────────────────────────────────────────────────────────────
create table if not exists public.closeout_packages (
  id              uuid    primary key default gen_random_uuid(),
  tenant_id       uuid    not null,
  project_id      uuid    not null references public.projects(id) on delete cascade,
  -- Required documents checklist (AI auto-generates this from project type)
  checklist       jsonb   not null default '[]',
  -- [{item, document_type, required, received, document_id, notes}]
  status          text    not null default 'not_started'
    check (status in ('not_started','in_progress','ready_for_submission','submitted','accepted')),
  pct_complete    integer not null default 0,
  -- Key dates
  target_date     date,
  submitted_at    timestamptz,
  accepted_at     timestamptz,
  -- Assembled document package URL (ZIP in Supabase Storage)
  package_url     text,
  package_built_at timestamptz,
  -- AI generation
  ai_generated    boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_closeout_packages_project on public.closeout_packages (project_id);

-- ────────────────────────────────────────────────────────────
-- VENDOR COMPLIANCE  (W-9, insurance tracking per vendor)
-- ────────────────────────────────────────────────────────────
create table if not exists public.vendor_compliance (
  id                    uuid    primary key default gen_random_uuid(),
  tenant_id             uuid    not null,
  subcontractor_company_id uuid references public.subcontractor_companies(id) on delete cascade,
  -- W-9 tracking (required for 1099 filing if payments >$600/yr)
  w9_on_file            boolean not null default false,
  w9_received_at        timestamptz,
  w9_document_id        uuid    references public.project_documents(id) on delete set null,
  tax_id_last4          text,   -- last 4 of EIN/SSN for verification
  -- Insurance certificate (ACORD 25)
  insurance_cert_on_file boolean not null default false,
  insurance_expires_at  timestamptz,
  insurance_document_id uuid    references public.project_documents(id) on delete set null,
  -- GL limit verified
  gl_limit_verified     numeric(14,2),
  -- License verification
  license_number        text,
  license_state         text,
  license_expires_at    date,
  license_verified_at   timestamptz,
  -- Performance bond
  bond_on_file          boolean not null default false,
  bond_amount           numeric(14,2),
  bond_surety           text,
  bond_expires_at       date,
  -- Overall compliance status
  is_compliant          boolean not null default false,
  compliance_notes      text,
  last_verified_at      timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_vendor_compliance_sub on public.vendor_compliance (tenant_id, subcontractor_company_id);
create index if not exists idx_vendor_compliance_insurance on public.vendor_compliance (insurance_expires_at)
  where insurance_cert_on_file = true;

-- ────────────────────────────────────────────────────────────
-- FORM AUTO-FILL LOG  (track every AI auto-population)
-- ────────────────────────────────────────────────────────────
create table if not exists public.form_autofill_log (
  id              uuid    primary key default gen_random_uuid(),
  tenant_id       uuid    not null,
  project_id      uuid,
  form_type       text    not null,  -- 'rfi', 'change_order', 'pay_app', 'lien_waiver', etc.
  entity_id       uuid,
  -- What AI filled
  fields_available integer not null default 0,   -- total fields in form
  fields_filled    integer not null default 0,   -- fields AI could fill
  fill_pct         integer generated always as
    (case when fields_available > 0 then 100 * fields_filled / fields_available else 0 end) stored,
  -- AI metadata
  ai_model         text,
  context_sources  jsonb not null default '[]',  -- ['project', 'contract', 'bid_jacket', ...]
  created_at       timestamptz not null default now()
);

-- ────────────────────────────────────────────────────────────
-- TRIGGERS
-- ────────────────────────────────────────────────────────────

do $$ begin create trigger trg_project_documents_updated_at before update on public.project_documents for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger trg_pay_applications_updated_at before update on public.pay_applications for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger trg_lien_waivers_updated_at before update on public.lien_waivers for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger trg_bid_documents_updated_at before update on public.bid_documents for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger trg_closeout_packages_updated_at before update on public.closeout_packages for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger trg_vendor_compliance_updated_at before update on public.vendor_compliance for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;

-- ────────────────────────────────────────────────────────────
-- ROW-LEVEL SECURITY
-- ────────────────────────────────────────────────────────────

alter table public.document_templates    enable row level security;
alter table public.project_documents     enable row level security;
alter table public.pay_applications      enable row level security;
alter table public.schedule_of_values    enable row level security;
alter table public.lien_waivers          enable row level security;
alter table public.bid_documents         enable row level security;
alter table public.closeout_packages     enable row level security;
alter table public.vendor_compliance     enable row level security;
alter table public.form_autofill_log     enable row level security;

create policy if not exists "document_templates are public read"
  on public.document_templates for select using (is_active = true);

create policy if not exists "tenant isolation on project_documents"
  on public.project_documents for all
  using (tenant_id = public.my_tenant_id())
  with check (tenant_id = public.my_tenant_id());

create policy if not exists "tenant isolation on pay_applications"
  on public.pay_applications for all
  using (tenant_id = public.my_tenant_id())
  with check (tenant_id = public.my_tenant_id());

create policy if not exists "tenant isolation on schedule_of_values"
  on public.schedule_of_values for all
  using (pay_application_id in (
    select id from public.pay_applications where tenant_id = public.my_tenant_id()
  ));

create policy if not exists "tenant isolation on lien_waivers"
  on public.lien_waivers for all
  using (tenant_id = public.my_tenant_id())
  with check (tenant_id = public.my_tenant_id());

create policy if not exists "tenant isolation on bid_documents"
  on public.bid_documents for all
  using (tenant_id = public.my_tenant_id())
  with check (tenant_id = public.my_tenant_id());

create policy if not exists "tenant isolation on closeout_packages"
  on public.closeout_packages for all
  using (tenant_id = public.my_tenant_id())
  with check (tenant_id = public.my_tenant_id());

create policy if not exists "tenant isolation on vendor_compliance"
  on public.vendor_compliance for all
  using (tenant_id = public.my_tenant_id())
  with check (tenant_id = public.my_tenant_id());

create policy if not exists "tenant isolation on form_autofill_log"
  on public.form_autofill_log for select
  using (tenant_id = public.my_tenant_id());

-- ────────────────────────────────────────────────────────────
-- VIEWS
-- ────────────────────────────────────────────────────────────

-- Project document completeness dashboard
create or replace view public.project_document_status as
select
  p.id                                              as project_id,
  p.tenant_id,
  p.name                                            as project_name,
  count(d.id)                                       as total_documents,
  count(d.id) filter (where d.status = 'signed')   as signed_documents,
  count(d.id) filter (where d.status = 'draft')    as draft_documents,
  count(d.id) filter (where d.requires_signature and d.signed_at is null) as awaiting_signature,
  count(lw.id)                                      as lien_waivers_total,
  count(lw.id) filter (where lw.status = 'signed') as lien_waivers_signed,
  max(pa.application_number)                        as latest_pay_app_number,
  sum(pa.current_payment_due) filter (where pa.status = 'approved') as approved_payment_due
from public.projects p
left join public.project_documents d   on d.project_id = p.id
left join public.lien_waivers lw       on lw.project_id = p.id
left join public.pay_applications pa   on pa.project_id = p.id
group by p.id, p.tenant_id, p.name;

-- Vendor compliance dashboard
create or replace view public.vendor_compliance_summary as
select
  vc.*,
  sc.name                       as company_name,
  sc.primary_email              as company_email,
  (vc.w9_on_file and vc.insurance_cert_on_file
   and (vc.insurance_expires_at is null or vc.insurance_expires_at > now())
   and (vc.license_expires_at is null or vc.license_expires_at > current_date))
                                as fully_compliant,
  case
    when vc.insurance_expires_at < now() + interval '30 days' then 'expiring_soon'
    when vc.insurance_expires_at < now()                       then 'expired'
    else 'current'
  end                           as insurance_status
from public.vendor_compliance vc
join public.subcontractor_companies sc on sc.id = vc.subcontractor_company_id;
