-- ============================================================
-- Saguaro CRM — Bid Intelligence & Auto-Project Creation
-- Migration: 20260308_bid_intelligence.sql
-- Run AFTER: 20260307_bid_portal.sql, 20260308_core_modules.sql
-- ============================================================
-- Adds the AI learning layer that makes Saguaro smarter over time:
--   bid_outcomes          — every bid result with AI analysis of why
--   bid_intelligence_profiles — rolling company "brain" per tenant
--   bid_opportunity_scores    — incoming opps scored by AI
--   auto_created_projects     — audit of what AI built per project
-- ============================================================

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

-- ────────────────────────────────────────────────────────────
-- BID OUTCOMES  (every bid tracked with AI post-mortem)
-- ────────────────────────────────────────────────────────────
create table if not exists public.bid_outcomes (
  id                        uuid    primary key default gen_random_uuid(),
  tenant_id                 uuid    not null,
  project_id                uuid,
  bid_submission_id         uuid    references public.bid_submissions(id) on delete set null,
  bid_package_id            uuid    references public.bid_packages(id)   on delete set null,

  -- What we bid on
  trade_category            text,   -- e.g. 'concrete','electrical','framing','mechanical'
  scope_summary             text,   -- brief description of scope we bid
  project_type              text,   -- 'commercial','residential','industrial','healthcare','education','government'
  project_size_sqft         integer,
  project_duration_days     integer,
  location                  text,
  owner_name                text,
  gc_name                   text,

  -- Our numbers
  bid_amount                numeric(14,2),
  estimated_cost            numeric(14,2),
  estimated_margin_percent  numeric(5,2),
  hours_spent_bidding       numeric(6,1),  -- time investment tracking

  -- Competitive context (fill in what you know)
  num_competitors_known     integer,
  winning_bid_amount        numeric(14,2),  -- null if unknown
  our_rank                  integer,        -- 1=won, 2=second, etc.
  winning_company           text,           -- who beat us (if known)

  -- Outcome
  outcome                   text    not null
    check (outcome in ('won','lost','no_bid','abandoned','pending')),
  outcome_date              date,
  lost_reason               text,   -- human-provided reason if lost

  -- AI Post-Mortem (generated by bid-intelligence.ts)
  ai_win_factors            jsonb,  -- [{factor, impact:'high'|'medium'|'low', detail}]
  ai_loss_factors           jsonb,  -- [{factor, impact, detail, corrective_action}]
  ai_price_analysis         jsonb,  -- {our_price_vs_market, strategy_used, recommended_strategy, adjustment_pct}
  ai_scope_fit_score        integer,  -- 0-100: how well the scope matched our strengths
  ai_relationship_score     integer,  -- 0-100: strength of relationship with owner/GC
  ai_lessons                jsonb,  -- [{lesson, recommendation, priority:'high'|'medium'|'low'}]
  ai_analysis_text          text,   -- full narrative analysis
  ai_model                  text,
  ai_analyzed_at            timestamptz,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_bid_outcomes_tenant
  on public.bid_outcomes (tenant_id, outcome, outcome_date desc);
create index if not exists idx_bid_outcomes_trade
  on public.bid_outcomes (tenant_id, trade_category, outcome);
create index if not exists idx_bid_outcomes_project_type
  on public.bid_outcomes (tenant_id, project_type, outcome);

-- ────────────────────────────────────────────────────────────
-- BID INTELLIGENCE PROFILES  (rolling AI-built company brain)
-- One row per tenant — updated after every batch of outcomes
-- ────────────────────────────────────────────────────────────
create table if not exists public.bid_intelligence_profiles (
  id            uuid    primary key default gen_random_uuid(),
  tenant_id     uuid    not null unique,

  -- Rolling stats
  total_bids            integer not null default 0,
  total_wins            integer not null default 0,
  total_losses          integer not null default 0,
  total_no_bids         integer not null default 0,
  win_rate_percent      numeric(5,2),
  avg_margin_won        numeric(5,2),   -- avg margin % on won bids
  avg_bid_amount        numeric(14,2),
  total_revenue_won     numeric(16,2),

  -- Trade-level stats (JSON map: trade → stats)
  -- {electrical:{bids:10,wins:7,win_rate:70,avg_margin:18,avg_bid:125000}}
  trade_stats           jsonb not null default '{}',

  -- Project type stats
  project_type_stats    jsonb not null default '{}',

  -- Size range performance
  -- {small:{<250k,bids,wins,win_rate}, medium:{250k-1M,...}, large:{>1M,...}}
  size_range_stats      jsonb not null default '{}',

  -- Relationship-driven wins (how much owner/GC relationship matters)
  relationship_win_rate numeric(5,2),  -- win rate when relationship score >=70

  -- AI-generated intelligence (updated on every profile rebuild)
  core_strengths        jsonb,  -- [{area, evidence, confidence_pct}]
  areas_to_improve      jsonb,  -- [{area, current_rate, target_rate, recommendation}]
  ideal_project_profile jsonb,  -- {trade_categories, project_types, size_range, owner_types, margin_target}

  -- Pricing intelligence
  avg_margin_by_trade   jsonb,  -- {electrical:18.2, concrete:12.5, ...}
  market_position       text    check (market_position in ('low_bidder','competitive','premium','unknown')),

  -- Actionable recommendations (rebuilt fresh each time)
  bid_strategy_text     text,   -- "Focus on healthcare and education — 73% win rate vs 42% for commercial"
  pricing_strategy_text text,   -- "You consistently win at 12-16% margin for electrical < $500k"
  scope_strategy_text   text,   -- "Avoid projects > 18 months — 8% win rate vs 48% for <12 months"
  top_recommendations   jsonb,  -- [{priority:1, action, rationale, expected_impact}] top 5

  -- Profile health
  profile_summary       text,   -- human-readable 3-4 paragraph intelligence brief
  data_quality          text    check (data_quality in ('insufficient','developing','solid','strong')),
  -- insufficient = <5 outcomes, developing = 5-20, solid = 21-50, strong = >50

  outcomes_analyzed     integer not null default 0,
  last_analyzed_at      timestamptz,
  next_analysis_due     timestamptz,  -- scheduled next rebuild

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ────────────────────────────────────────────────────────────
-- BID OPPORTUNITY SCORES  (incoming opps evaluated by AI)
-- ────────────────────────────────────────────────────────────
create table if not exists public.bid_opportunity_scores (
  id               uuid    primary key default gen_random_uuid(),
  tenant_id        uuid    not null,

  -- Opportunity details (input)
  opportunity_title       text    not null,
  opportunity_description text,
  trade_category          text,
  project_type            text,
  location                text,
  estimated_value         numeric(14,2),
  bid_due_date            date,
  project_start_date      date,
  project_duration_days   integer,
  owner_name              text,
  gc_name                 text,
  source                  text,   -- 'manual','email','construction_connect','dodge','government','referral'
  source_url              text,

  -- AI Scoring output
  fit_score               integer,        -- 0-100 overall fit to company profile
  win_probability         integer,        -- 0-100 estimated win probability
  recommended_action      text
    check (recommended_action in ('bid','pass','partner','investigate','bid_with_partner')),

  -- Score breakdown
  scope_alignment_score   integer,   -- 0-100 how well scope matches our strengths
  capacity_score          integer,   -- 0-100 do we have bandwidth/resources
  relationship_score      integer,   -- 0-100 strength of relationship with owner/GC
  competition_score       integer,   -- 0-100 lower competition = higher score
  margin_potential_score  integer,   -- 0-100 margin opportunity vs our average

  -- Pricing recommendation
  suggested_bid_low       numeric(14,2),
  suggested_bid_high      numeric(14,2),
  suggested_margin_pct    numeric(5,2),

  -- AI Analysis text
  bid_recommendation_text text,  -- full analysis and recommendation
  why_we_win              jsonb, -- [{reason, confidence:'high'|'medium'|'low'}]
  key_risks               jsonb, -- [{risk, mitigation, severity}]
  similar_past_wins       jsonb, -- [{outcome_id, similarity_pct, what_worked}]
  similar_past_losses     jsonb, -- [{outcome_id, similarity_pct, lesson}]

  -- Tracking
  status                  text not null default 'new'
    check (status in ('new','reviewing','bidding','won','lost','passed','no_bid')),
  linked_bid_package_id   uuid    references public.bid_packages(id) on delete set null,
  linked_outcome_id       uuid    references public.bid_outcomes(id) on delete set null,

  ai_model                text,
  ai_analyzed_at          timestamptz,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_bid_opportunity_scores_tenant
  on public.bid_opportunity_scores (tenant_id, fit_score desc, status);
create index if not exists idx_bid_opportunity_scores_due
  on public.bid_opportunity_scores (tenant_id, bid_due_date asc)
  where status in ('new','reviewing','bidding');

-- ────────────────────────────────────────────────────────────
-- AUTO CREATED PROJECTS  (audit of what AI built per project)
-- ────────────────────────────────────────────────────────────
create table if not exists public.auto_created_projects (
  id                      uuid    primary key default gen_random_uuid(),
  tenant_id               uuid    not null,
  project_id              uuid    not null,
  bid_submission_id       uuid    references public.bid_submissions(id) on delete set null,
  contract_id             uuid    references public.contracts(id)       on delete set null,

  -- Counts of what was auto-created
  schedule_tasks_created  integer not null default 0,
  budget_lines_created    integer not null default 0,
  contacts_created        integer not null default 0,
  subpackages_created     integer not null default 0,  -- sub bid packages created

  -- Flags for what was initialized
  rfi_log_initialized     boolean not null default false,
  safety_plan_created     boolean not null default false,
  qc_checklist_created    boolean not null default false,
  document_structure_created boolean not null default false,

  -- AI metadata
  ai_model                text,
  ai_prompt_tokens        integer,
  ai_output_tokens        integer,
  creation_summary        text,   -- brief of what was created
  creation_warnings       jsonb,  -- any items that couldn't be auto-created

  created_at  timestamptz not null default now()
);

create index if not exists idx_auto_created_projects_project
  on public.auto_created_projects (tenant_id, project_id);

-- ────────────────────────────────────────────────────────────
-- TRIGGERS
-- ────────────────────────────────────────────────────────────

do $$ begin
  create trigger trg_bid_outcomes_updated_at
    before update on public.bid_outcomes
    for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_bid_intelligence_profiles_updated_at
    before update on public.bid_intelligence_profiles
    for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_bid_opportunity_scores_updated_at
    before update on public.bid_opportunity_scores
    for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

-- ────────────────────────────────────────────────────────────
-- ROW-LEVEL SECURITY
-- ────────────────────────────────────────────────────────────

alter table public.bid_outcomes               enable row level security;
alter table public.bid_intelligence_profiles  enable row level security;
alter table public.bid_opportunity_scores     enable row level security;
alter table public.auto_created_projects      enable row level security;

create policy if not exists "tenant members manage bid outcomes"
  on public.bid_outcomes for all
  using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid)
  with check (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

create policy if not exists "tenant members manage bid intelligence profile"
  on public.bid_intelligence_profiles for all
  using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid)
  with check (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

create policy if not exists "tenant members manage bid opportunity scores"
  on public.bid_opportunity_scores for all
  using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid)
  with check (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

create policy if not exists "tenant members view auto created projects"
  on public.auto_created_projects for select
  using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);

-- ────────────────────────────────────────────────────────────
-- VIEWS
-- ────────────────────────────────────────────────────────────

-- Win/loss dashboard by trade
create or replace view public.bid_win_rate_by_trade as
select
  tenant_id,
  trade_category,
  count(*)                                              as total_bids,
  count(*) filter (where outcome = 'won')              as wins,
  count(*) filter (where outcome = 'lost')             as losses,
  round(
    100.0 * count(*) filter (where outcome = 'won')
    / nullif(count(*) filter (where outcome in ('won','lost')), 0),
    1
  )                                                     as win_rate_pct,
  round(avg(estimated_margin_percent) filter (where outcome = 'won'), 1) as avg_winning_margin,
  round(avg(bid_amount), 0)                            as avg_bid_amount
from public.bid_outcomes
where outcome in ('won','lost')
group by 1, 2
order by 1, win_rate_pct desc;

-- Top opportunity pipeline
create or replace view public.bid_opportunity_pipeline as
select
  tenant_id,
  opportunity_title,
  trade_category,
  estimated_value,
  bid_due_date,
  fit_score,
  win_probability,
  recommended_action,
  status,
  created_at
from public.bid_opportunity_scores
where status in ('new','reviewing','bidding')
order by fit_score desc, bid_due_date asc;
