'use client';
/**
 * Saguaro Field — RFI View / Respond
 * List, view detail, respond to, and create RFIs from the field.
 */
import React, { useState, useEffect, useRef, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { enqueue } from '@/lib/field-db';
import EmailComposer from '@/components/EmailComposer';

const GOLD   = '#C8960F';
const RAISED = '#0D1D2E';
const BORDER = '#1E3A5F';
const TEXT   = '#F0F4FF';
const DIM    = '#8BAAC8';
const GREEN  = '#22C55E';
const RED    = '#EF4444';
const AMBER  = '#F59E0B';
const BLUE   = '#3B82F6';
const PURPLE = '#8B5CF6';

const SPEC_SECTIONS = [
  'Division 01 – Gen. Requirements', 'Division 03 – Concrete', 'Division 04 – Masonry',
  'Division 05 – Metals', 'Division 06 – Wood & Plastics', 'Division 07 – Thermal',
  'Division 08 – Openings', 'Division 09 – Finishes', 'Division 22 – Plumbing',
  'Division 23 – HVAC', 'Division 26 – Electrical', 'Other',
];

interface RFI {
  id: string;
  rfi_number?: number;
  subject: string;
  question: string;
  status: string;
  priority?: string;
  assigned_to?: string;
  due_date?: string;
  created_at?: string;
  spec_section?: string;
  attachments?: Array<{ name: string; url: string }>;
  responses?: Array<{ author: string; text: string; created_at: string; attachments?: Array<{ name: string; url: string }> }>;
}

type View = 'list' | 'detail' | 'create';

function statusColor(status: string): string {
  const s = status?.toLowerCase() || '';
  if (s === 'open' || s === 'pending') return BLUE;
  if (s === 'answered' || s === 'closed' || s === 'resolved') return GREEN;
  if (s === 'overdue') return RED;
  if (s === 'draft') return DIM;
  if (s === 'void') return '#6B7280';
  return DIM;
}

function priorityColor(priority: string): string {
  const p = priority?.toLowerCase() || '';
  if (p === 'critical') return RED;
  if (p === 'high') return AMBER;
  if (p === 'medium') return BLUE;
  if (p === 'low') return GREEN;
  return DIM;
}

const PRIORITY_RANK: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1 };
const STATUS_RANK: Record<string, number> = { open: 4, draft: 3, closed: 2, void: 1 };

interface FilterState {
  statuses: string[];
  priorities: string[];
  assignee: string;
  dateFrom: string;
  dateTo: string;
  sortBy: string;
  sortDir: 'asc' | 'desc';
}

interface SavedPreset {
  name: string;
  filter: FilterState;
}

function formatDate(d: string | undefined): string {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

const exportPDF = (title: string, content: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1a1a1a; max-width: 800px; margin: 0 auto; }
        h1 { font-size: 24px; border-bottom: 2px solid #C8960F; padding-bottom: 8px; }
        h2 { font-size: 18px; color: #333; margin-top: 24px; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; font-size: 13px; }
        th { background: #f5f5f5; font-weight: 600; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
        .meta { color: #666; font-size: 13px; }
        .section { margin: 16px 0; padding: 12px; border: 1px solid #eee; border-radius: 8px; }
        img { max-width: 300px; margin: 4px; border-radius: 4px; }
        .signature { max-width: 200px; border: 1px solid #ddd; border-radius: 4px; padding: 4px; }
        .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 11px; color: #999; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">
        <p>Generated by Saguaro Control &middot; ${new Date().toLocaleString()}</p>
      </div>
    </body>
    </html>
  `);
  printWindow.document.close();
  setTimeout(() => printWindow.print(), 500);
};

const PdfIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}>
    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1={12} y1={18} x2={12} y2={12}/><polyline points="9 15 12 12 15 15"/>
  </svg>
);

function RFIsPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const projectId = searchParams.get('projectId') || '';

  const [rfis, setRfis] = useState<RFI[]>([]);
  const [loading, setLoading] = useState(true);
  const [view, setView] = useState<View>('list');
  const [selectedRfi, setSelectedRfi] = useState<RFI | null>(null);
  const [online, setOnline] = useState(true);

  // Bulk selection state
  const [selectMode, setSelectMode] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [bulkAction, setBulkAction] = useState<string | null>(null);
  const [showReassignPicker, setShowReassignPicker] = useState(false);
  const [reassignTo, setReassignTo] = useState('');
  const [bulkProcessing, setBulkProcessing] = useState(false);
  const [confirmDialog, setConfirmDialog] = useState<{ title: string; message: string; action: () => void } | null>(null);

  const toggleSelectId = (id: string) => {
    setSelectedIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };
  const selectAll = () => setSelectedIds(new Set(rfis.map(r => r.id)));
  const deselectAll = () => setSelectedIds(new Set());

  const handleBulkClose = async () => {
    setBulkProcessing(true);
    const ids = Array.from(selectedIds);
    for (const id of ids) {
      try {
        if (!online) throw new Error('offline');
        await fetch(`/api/rfis/${id}/status`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ status: 'closed' }),
        });
      } catch {
        await enqueue({
          url: `/api/rfis/${id}/status`,
          method: 'PATCH',
          body: JSON.stringify({ status: 'closed' }),
          contentType: 'application/json',
          isFormData: false,
        });
      }
    }
    setRfis(prev => prev.map(r => ids.includes(r.id) ? { ...r, status: 'closed' } : r));
    setSelectedIds(new Set());
    setSelectMode(false);
    setBulkProcessing(false);
    setSubmitMsg(`${ids.length} RFI(s) closed`);
    setTimeout(() => setSubmitMsg(''), 3500);
  };

  const handleBulkReassign = async () => {
    if (!reassignTo.trim()) return;
    setBulkProcessing(true);
    const ids = Array.from(selectedIds);
    for (const id of ids) {
      try {
        if (!online) throw new Error('offline');
        await fetch(`/api/rfis/${id}/reassign`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ assigned_to: reassignTo.trim() }),
        });
      } catch {
        await enqueue({
          url: `/api/rfis/${id}/reassign`,
          method: 'PATCH',
          body: JSON.stringify({ assigned_to: reassignTo.trim() }),
          contentType: 'application/json',
          isFormData: false,
        });
      }
    }
    setSelectedIds(new Set());
    setSelectMode(false);
    setShowReassignPicker(false);
    setReassignTo('');
    setBulkProcessing(false);
    setSubmitMsg(`${ids.length} RFI(s) reassigned to ${reassignTo.trim()}`);
    setTimeout(() => setSubmitMsg(''), 3500);
  };

  const handleBulkExport = async () => {
    setBulkProcessing(true);
    const ids = Array.from(selectedIds);
    try {
      if (!online) throw new Error('offline');
      const res = await fetch(`/api/projects/${projectId}/rfis/export`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ rfi_ids: ids }),
      });
      if (res.ok) {
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `rfis-export-${Date.now()}.pdf`;
        a.click();
        URL.revokeObjectURL(url);
        setSubmitMsg(`${ids.length} RFI(s) exported`);
      } else {
        setSubmitMsg('Export failed');
      }
    } catch {
      await enqueue({
        url: `/api/projects/${projectId}/rfis/export`,
        method: 'POST',
        body: JSON.stringify({ rfi_ids: ids }),
        contentType: 'application/json',
        isFormData: false,
      });
      setSubmitMsg('Export queued — will download when online');
    }
    setSelectedIds(new Set());
    setSelectMode(false);
    setBulkProcessing(false);
    setTimeout(() => setSubmitMsg(''), 3500);
  };

  // Email composer
  const [showEmail, setShowEmail] = useState(false);

  // Response form
  const [responseText, setResponseText] = useState('');
  const [responsePhoto, setResponsePhoto] = useState<File | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitMsg, setSubmitMsg] = useState('');
  const photoInputRef = useRef<HTMLInputElement>(null);

  // Create form
  const [newSubject, setNewSubject] = useState('');
  const [newQuestion, setNewQuestion] = useState('');
  const [newSpec, setNewSpec] = useState('Other');
  const [newDueDate, setNewDueDate] = useState('');

  // ─── Advanced Filters & Sorting ─────────────────────────────
  const [filterStatuses, setFilterStatuses] = useState<string[]>([]);
  const [filterPriorities, setFilterPriorities] = useState<string[]>([]);
  const [filterAssignee, setFilterAssignee] = useState('');
  const [filterDateFrom, setFilterDateFrom] = useState('');
  const [filterDateTo, setFilterDateTo] = useState('');
  const [sortBy, setSortBy] = useState<'date_created' | 'due_date' | 'priority' | 'status'>('date_created');
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc');
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [savedPresets, setSavedPresets] = useState<SavedPreset[]>([]);
  const [presetName, setPresetName] = useState('');
  const RFI_FILTER_STATUSES = ['Draft', 'Open', 'Closed', 'Void'];
  const RFI_FILTER_PRIORITIES = ['Low', 'Medium', 'High', 'Critical'];

  useEffect(() => {
    try {
      const raw = localStorage.getItem(`saguaro_rfi_presets_${projectId}`);
      if (raw) setSavedPresets(JSON.parse(raw));
    } catch { /* */ }
  }, [projectId]);

  const persistPresets = (p: SavedPreset[]) => {
    setSavedPresets(p);
    try { localStorage.setItem(`saguaro_rfi_presets_${projectId}`, JSON.stringify(p)); } catch { /* */ }
  };

  const getCurrentFilterState = (): FilterState => ({
    statuses: filterStatuses,
    priorities: filterPriorities,
    assignee: filterAssignee,
    dateFrom: filterDateFrom,
    dateTo: filterDateTo,
    sortBy,
    sortDir,
  });

  const applyFilterState = (f: FilterState) => {
    setFilterStatuses(f.statuses || []);
    setFilterPriorities(f.priorities || []);
    setFilterAssignee(f.assignee || '');
    setFilterDateFrom(f.dateFrom || '');
    setFilterDateTo(f.dateTo || '');
    setSortBy((f.sortBy as typeof sortBy) || 'date_created');
    setSortDir(f.sortDir || 'desc');
  };

  const saveCurrentPreset = () => {
    if (!presetName.trim()) return;
    persistPresets([...savedPresets, { name: presetName.trim(), filter: getCurrentFilterState() }]);
    setPresetName('');
  };

  const deletePreset = (idx: number) => persistPresets(savedPresets.filter((_, i) => i !== idx));

  const clearAllFilters = () => {
    setFilterStatuses([]);
    setFilterPriorities([]);
    setFilterAssignee('');
    setFilterDateFrom('');
    setFilterDateTo('');
    setSortBy('date_created');
    setSortDir('desc');
  };

  const toggleArrFilter = (arr: string[], val: string, setter: React.Dispatch<React.SetStateAction<string[]>>) =>
    setter(arr.includes(val) ? arr.filter(v => v !== val) : [...arr, val]);

  const activeFilterCount = [
    filterStatuses.length > 0,
    filterPriorities.length > 0,
    !!filterAssignee,
    !!filterDateFrom || !!filterDateTo,
  ].filter(Boolean).length;

  const getFilteredRfis = (): RFI[] => {
    let result = [...rfis];
    // Status filter
    if (filterStatuses.length > 0) {
      result = result.filter(r => {
        const s = (r.status || '').toLowerCase();
        return filterStatuses.some(fs => {
          const fl = fs.toLowerCase();
          if (fl === 'closed') return s === 'closed' || s === 'answered' || s === 'resolved';
          return s === fl;
        });
      });
    }
    // Priority filter
    if (filterPriorities.length > 0) {
      result = result.filter(r => {
        const p = (r.priority || '').toLowerCase();
        return filterPriorities.some(fp => fp.toLowerCase() === p);
      });
    }
    // Assigned To filter
    if (filterAssignee.trim()) {
      const needle = filterAssignee.trim().toLowerCase();
      result = result.filter(r =>
        (r.assigned_to || '').toLowerCase().includes(needle)
      );
    }
    // Date range on created_at
    if (filterDateFrom || filterDateTo) {
      result = result.filter(r => {
        const d = r.created_at;
        if (!d) return false;
        const dt = new Date(d).getTime();
        if (filterDateFrom && dt < new Date(filterDateFrom).getTime()) return false;
        if (filterDateTo && dt > new Date(filterDateTo + 'T23:59:59').getTime()) return false;
        return true;
      });
    }
    // Sorting
    const dir = sortDir === 'asc' ? 1 : -1;
    result.sort((a, b) => {
      if (sortBy === 'date_created') {
        return dir * (new Date(a.created_at || 0).getTime() - new Date(b.created_at || 0).getTime());
      }
      if (sortBy === 'due_date') {
        if (!a.due_date && !b.due_date) return 0;
        if (!a.due_date) return 1;
        if (!b.due_date) return -1;
        return dir * (new Date(a.due_date).getTime() - new Date(b.due_date).getTime());
      }
      if (sortBy === 'priority') {
        const pa = PRIORITY_RANK[(a.priority || '').toLowerCase()] || 0;
        const pb = PRIORITY_RANK[(b.priority || '').toLowerCase()] || 0;
        return dir * (pa - pb);
      }
      if (sortBy === 'status') {
        const sa = STATUS_RANK[(a.status || '').toLowerCase()] || 0;
        const sb = STATUS_RANK[(b.status || '').toLowerCase()] || 0;
        return dir * (sa - sb);
      }
      return 0;
    });
    return result;
  };

  const applyQuickPreset = (key: string) => {
    clearAllFilters();
    if (key === 'open_rfis') {
      setFilterStatuses(['Open']);
      setSortBy('date_created');
      setSortDir('desc');
    } else if (key === 'overdue') {
      // Show open RFIs sorted by due date ascending so most overdue appear first
      setFilterStatuses(['Open']);
      setSortBy('due_date');
      setSortDir('asc');
    } else if (key === 'my_rfis') {
      setFilterAssignee('me');
      setSortBy('date_created');
      setSortDir('desc');
    } else if (key === 'high_priority') {
      setFilterPriorities(['High', 'Critical']);
      setSortBy('priority');
      setSortDir('desc');
    }
  };

  const filteredRfis = getFilteredRfis();
  const chipStyle: React.CSSProperties = {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    background: 'rgba(139,92,246,.12)', border: `1px solid rgba(139,92,246,.3)`,
    borderRadius: 20, padding: '4px 10px', fontSize: 11, fontWeight: 600,
    color: PURPLE, cursor: 'pointer', whiteSpace: 'nowrap',
  };

  useEffect(() => {
    setOnline(navigator.onLine);
    const on = () => setOnline(true);
    const off = () => setOnline(false);
    window.addEventListener('online', on);
    window.addEventListener('offline', off);
    return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off); };
  }, []);

  useEffect(() => {
    if (!projectId) { setLoading(false); return; }
    fetch(`/api/rfis/list?projectId=${projectId}`)
      .then((r) => r.ok ? r.json() : { rfis: [] })
      .then((d) => setRfis(d.rfis || d.items || []))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [projectId]);

  const openDetail = (rfi: RFI) => {
    setSelectedRfi(rfi);
    setView('detail');
    setResponseText('');
    setResponsePhoto(null);
    setSubmitMsg('');
  };

  const handleRespond = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedRfi || !responseText.trim()) return;
    setSubmitting(true);

    const payload: Record<string, string> = {
      answer: responseText.trim(),
    };

    // If there is a photo, we handle it as FormData
    if (responsePhoto) {
      try {
        const fd = new FormData();
        fd.append('answer', responseText.trim());
        fd.append('photo', responsePhoto);

        if (!online) throw new Error('offline');
        const res = await fetch(`/api/rfis/${selectedRfi.id}/respond`, { method: 'POST', body: fd });
        if (!res.ok) throw new Error();
        setSubmitMsg('Response submitted');

        // Optimistically add the response
        setSelectedRfi((prev) => prev ? {
          ...prev,
          responses: [...(prev.responses || []), { author: 'You (field)', text: responseText.trim(), created_at: new Date().toISOString() }],
        } : prev);
        setRfis((prev) => prev.map((r) => r.id === selectedRfi.id ? { ...r, status: 'answered' } : r));
      } catch {
        // Queue with base64 photo
        const reader = new FileReader();
        reader.onload = async () => {
          const base64 = (reader.result as string).split(',')[1] || '';
          await enqueue({
            url: `/api/rfis/${selectedRfi.id}/respond`,
            method: 'POST',
            body: null,
            contentType: '',
            isFormData: true,
            formDataEntries: [
              { name: 'answer', value: responseText.trim() },
              { name: 'photo', value: base64, filename: responsePhoto.name, type: responsePhoto.type },
            ],
          });
          setSubmitMsg('Response queued — will sync when online');
        };
        reader.readAsDataURL(responsePhoto);
      }
    } else {
      try {
        if (!online) throw new Error('offline');
        const res = await fetch(`/api/rfis/${selectedRfi.id}/respond`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
        if (!res.ok) throw new Error();
        setSubmitMsg('Response submitted');
        setSelectedRfi((prev) => prev ? {
          ...prev,
          responses: [...(prev.responses || []), { author: 'You (field)', text: responseText.trim(), created_at: new Date().toISOString() }],
        } : prev);
        setRfis((prev) => prev.map((r) => r.id === selectedRfi.id ? { ...r, status: 'answered' } : r));
      } catch {
        await enqueue({
          url: `/api/rfis/${selectedRfi.id}/respond`,
          method: 'POST',
          body: JSON.stringify(payload),
          contentType: 'application/json',
          isFormData: false,
        });
        setSubmitMsg('Response queued — will sync when online');
      }
    }

    setResponseText('');
    setResponsePhoto(null);
    setSubmitting(false);
    setTimeout(() => setSubmitMsg(''), 3500);
  };

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newSubject.trim() || !newQuestion.trim()) return;
    setSubmitting(true);

    const payload = {
      projectId,
      subject: newSubject.trim(),
      question: newQuestion.trim(),
      specSection: newSpec,
      dueDate: newDueDate || null,
    };

    try {
      if (!online) throw new Error('offline');
      const res = await fetch('/api/rfis/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error();

      const data = await res.json().catch(() => ({}));
      const newRfi: RFI = {
        id: data.id || `temp-${Date.now()}`,
        subject: newSubject.trim(),
        question: newQuestion.trim(),
        status: 'open',
        spec_section: newSpec,
        due_date: newDueDate || undefined,
        created_at: new Date().toISOString(),
        rfi_number: (rfis.length + 1),
        responses: [],
      };
      setRfis((prev) => [newRfi, ...prev]);
      setSubmitMsg('RFI created');
    } catch {
      await enqueue({
        url: '/api/rfis/create',
        method: 'POST',
        body: JSON.stringify(payload),
        contentType: 'application/json',
        isFormData: false,
      });
      const newRfi: RFI = {
        id: `queued-${Date.now()}`,
        subject: newSubject.trim(),
        question: newQuestion.trim(),
        status: 'open',
        spec_section: newSpec,
        due_date: newDueDate || undefined,
        created_at: new Date().toISOString(),
        rfi_number: (rfis.length + 1),
        responses: [],
      };
      setRfis((prev) => [newRfi, ...prev]);
      setSubmitMsg('RFI queued — will sync when online');
    }

    setNewSubject('');
    setNewQuestion('');
    setNewDueDate('');
    setSubmitting(false);
    setView('list');
    setTimeout(() => setSubmitMsg(''), 3500);
  };

  // ─── LIST VIEW ────────────────────────────────────────────────
  if (view === 'list') {
    return (
      <div style={{ padding: '18px 16px' }}>
        <button onClick={() => router.back()} style={backBtn}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round" width={22} height={22}>
            <line x1={19} y1={12} x2={5} y2={12}/><polyline points="12 19 5 12 12 5"/>
          </svg>
        </button>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
          <div>
            <h1 style={{ margin: '0 0 2px', fontSize: 22, fontWeight: 800, color: TEXT }}>RFIs</h1>
            <p style={{ margin: 0, fontSize: 13, color: DIM }}>Requests for Information</p>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            {rfis.length > 0 && (
              <button onClick={() => { setSelectMode(!selectMode); setSelectedIds(new Set()); }} style={{
                background: selectMode ? 'rgba(139,92,246,.2)' : 'transparent', border: `1px solid ${selectMode ? PURPLE : BORDER}`,
                borderRadius: 10, padding: '10px 14px', color: selectMode ? PURPLE : DIM, fontSize: 13, fontWeight: 600, cursor: 'pointer',
              }}>
                {selectMode ? 'Cancel' : 'Select'}
              </button>
            )}
            <button onClick={() => { setView('create'); setSubmitMsg(''); }} style={{
              background: PURPLE, border: 'none', borderRadius: 10, padding: '10px 16px',
              color: '#fff', fontSize: 14, fontWeight: 700, cursor: 'pointer',
            }}>
              + New RFI
            </button>
          </div>
        </div>

        {selectMode && rfis.length > 0 && (
          <div style={{ display: 'flex', gap: 8, marginBottom: 12, alignItems: 'center' }}>
            <button onClick={selectedIds.size === rfis.length ? deselectAll : selectAll} style={{
              background: 'rgba(139,92,246,.1)', border: `1px solid rgba(139,92,246,.3)`, borderRadius: 8,
              padding: '6px 14px', color: PURPLE, fontSize: 12, fontWeight: 700, cursor: 'pointer',
            }}>
              {selectedIds.size === rfis.length ? 'Deselect All' : 'Select All'}
            </button>
            <span style={{ fontSize: 12, color: DIM }}>{selectedIds.size} selected</span>
          </div>
        )}

        {!online && <div style={{ background: 'rgba(239,68,68,.1)', border: '1px solid rgba(239,68,68,.25)', borderRadius: 8, padding: '8px 12px', marginBottom: 14, fontSize: 13, color: RED, fontWeight: 600 }}>Offline — showing cached data</div>}

        {submitMsg && (
          <div style={{ background: 'rgba(34,197,94,.1)', border: '1px solid rgba(34,197,94,.3)', borderRadius: 10, padding: '12px 14px', marginBottom: 14, color: GREEN, fontSize: 14, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 8 }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}><polyline points="20 6 9 17 4 12"/></svg>{submitMsg}
          </div>
        )}

        {/* ─── Filter Bar ─── */}
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 10 }}>
          <button onClick={() => setDrawerOpen(true)} style={{
            background: activeFilterCount > 0 ? 'rgba(212,160,23,.15)' : 'transparent',
            border: `1px solid ${activeFilterCount > 0 ? GOLD : BORDER}`,
            borderRadius: 10, padding: '8px 14px', color: activeFilterCount > 0 ? GOLD : DIM,
            fontSize: 13, fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6,
          }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/></svg>
            Filters {activeFilterCount > 0 ? `(${activeFilterCount})` : ''}
          </button>
          {activeFilterCount > 0 && (
            <button onClick={clearAllFilters} style={{
              background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 10,
              padding: '8px 12px', color: DIM, fontSize: 12, fontWeight: 600, cursor: 'pointer',
            }}>Clear All</button>
          )}
          <span style={{ marginLeft: 'auto', fontSize: 12, color: activeFilterCount > 0 ? GOLD : DIM, fontWeight: 600 }}>
            {activeFilterCount > 0 ? `${filteredRfis.length} of ${rfis.length} results` : `${rfis.length} RFIs`}
          </span>
        </div>

        {/* ─── Filter Drawer (slides from right) ─── */}
        {drawerOpen && (
          <div style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 300,
            display: 'flex', justifyContent: 'flex-end',
          }}>
            {/* Backdrop */}
            <div
              onClick={() => setDrawerOpen(false)}
              style={{
                position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
                background: 'rgba(0,0,0,.1)', backdropFilter: 'blur(2px)',
              }}
            />
            {/* Drawer panel */}
            <div style={{
              position: 'relative', width: '100%', maxWidth: 380,
              background: '#07101C', borderLeft: `1px solid ${BORDER}`,
              display: 'flex', flexDirection: 'column', overflowY: 'auto',
              animation: 'none',
            }}>
              {/* Drawer header */}
              <div style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '16px 18px', borderBottom: `1px solid ${BORDER}`,
                position: 'sticky', top: 0, background: '#07101C', zIndex: 1,
              }}>
                <h2 style={{ margin: 0, fontSize: 18, fontWeight: 800, color: TEXT }}>Filters &amp; Sort</h2>
                <button onClick={() => setDrawerOpen(false)} style={{
                  background: 'none', border: 'none', color: DIM, cursor: 'pointer', padding: 4, fontSize: 22, lineHeight: 1,
                }}>&times;</button>
              </div>

              <div style={{ padding: '14px 18px', flex: 1 }}>
                {/* Quick Presets */}
                <div style={{ marginBottom: 18 }}>
                  <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8, color: GOLD, marginBottom: 8 }}>Quick Presets</label>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    {[
                      { key: 'open_rfis', label: 'Open RFIs' },
                      { key: 'overdue', label: 'Overdue' },
                      { key: 'my_rfis', label: 'My RFIs' },
                      { key: 'high_priority', label: 'High Priority' },
                    ].map(qp => (
                      <button key={qp.key} onClick={() => applyQuickPreset(qp.key)} style={{
                        background: 'rgba(212,160,23,.08)', border: `1px solid rgba(212,160,23,.3)`,
                        borderRadius: 20, padding: '6px 14px', color: GOLD,
                        fontSize: 12, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap' as const,
                      }}>{qp.label}</button>
                    ))}
                  </div>
                </div>

                {/* Status multi-select */}
                <div style={{ marginBottom: 18 }}>
                  <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Status</label>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    {RFI_FILTER_STATUSES.map(s => {
                      const active = filterStatuses.includes(s);
                      return (
                        <button key={s} onClick={() => toggleArrFilter(filterStatuses, s, setFilterStatuses)} style={{
                          background: active ? `rgba(${hexRgb(statusColor(s.toLowerCase()))},.18)` : 'transparent',
                          border: `1px solid ${active ? statusColor(s.toLowerCase()) : BORDER}`, borderRadius: 20,
                          padding: '6px 14px', color: active ? statusColor(s.toLowerCase()) : DIM, fontSize: 12,
                          fontWeight: active ? 700 : 500, cursor: 'pointer', whiteSpace: 'nowrap' as const,
                        }}>{s}</button>
                      );
                    })}
                  </div>
                </div>

                {/* Priority multi-select */}
                <div style={{ marginBottom: 18 }}>
                  <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Priority</label>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    {RFI_FILTER_PRIORITIES.map(p => {
                      const active = filterPriorities.includes(p);
                      return (
                        <button key={p} onClick={() => toggleArrFilter(filterPriorities, p, setFilterPriorities)} style={{
                          background: active ? `rgba(${hexRgb(priorityColor(p))},.18)` : 'transparent',
                          border: `1px solid ${active ? priorityColor(p) : BORDER}`, borderRadius: 20,
                          padding: '6px 14px', color: active ? priorityColor(p) : DIM, fontSize: 12,
                          fontWeight: active ? 700 : 500, cursor: 'pointer', whiteSpace: 'nowrap' as const,
                        }}>{p}</button>
                      );
                    })}
                  </div>
                </div>

                {/* Assigned To */}
                <div style={{ marginBottom: 18 }}>
                  <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Assigned To</label>
                  <input
                    value={filterAssignee}
                    onChange={e => setFilterAssignee(e.target.value)}
                    placeholder="Search by name or email..."
                    style={{ ...inp, fontSize: 13, padding: '10px 14px' }}
                  />
                </div>

                {/* Date range (Created Date) */}
                <div style={{ marginBottom: 18 }}>
                  <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Created Date Range</label>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <div style={{ flex: 1 }}>
                      <label style={{ ...lbl, fontSize: 10, marginBottom: 2 }}>From</label>
                      <input type="date" value={filterDateFrom} onChange={e => setFilterDateFrom(e.target.value)} style={{ ...inp, fontSize: 12, padding: '8px 10px' }} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <label style={{ ...lbl, fontSize: 10, marginBottom: 2 }}>To</label>
                      <input type="date" value={filterDateTo} onChange={e => setFilterDateTo(e.target.value)} style={{ ...inp, fontSize: 12, padding: '8px 10px' }} />
                    </div>
                  </div>
                </div>

                {/* Sort By with asc/desc toggle */}
                <div style={{ marginBottom: 18 }}>
                  <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Sort By</label>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <select value={sortBy} onChange={e => setSortBy(e.target.value as typeof sortBy)} style={{ ...inp, fontSize: 13, padding: '10px 14px', flex: 1 }}>
                      <option value="date_created">Date Created</option>
                      <option value="due_date">Due Date</option>
                      <option value="priority">Priority</option>
                      <option value="status">Status</option>
                    </select>
                    <button onClick={() => setSortDir(prev => prev === 'asc' ? 'desc' : 'asc')} style={{
                      background: 'rgba(212,160,23,.08)', border: `1px solid rgba(212,160,23,.3)`,
                      borderRadius: 10, padding: '10px 14px', color: GOLD, fontSize: 13,
                      fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4,
                      minWidth: 70, justifyContent: 'center',
                    }}>
                      {sortDir === 'asc' ? (
                        <><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><line x1={12} y1={19} x2={12} y2={5}/><polyline points="5 12 12 5 19 12"/></svg> ASC</>
                      ) : (
                        <><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><line x1={12} y1={5} x2={12} y2={19}/><polyline points="19 12 12 19 5 12"/></svg> DESC</>
                      )}
                    </button>
                  </div>
                </div>

                {/* Divider */}
                <div style={{ borderTop: `1px solid ${BORDER}`, margin: '8px 0 16px' }} />

                {/* Save Preset */}
                <div style={{ marginBottom: 18 }}>
                  <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8, color: GOLD }}>Save Current as Preset</label>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <input
                      value={presetName}
                      onChange={e => setPresetName(e.target.value)}
                      placeholder="Preset name..."
                      style={{ ...inp, fontSize: 13, padding: '10px 14px', flex: 1 }}
                      onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); saveCurrentPreset(); } }}
                    />
                    <button onClick={saveCurrentPreset} disabled={!presetName.trim()} style={{
                      background: presetName.trim() ? GOLD : BORDER, border: 'none', borderRadius: 10,
                      padding: '10px 18px', color: presetName.trim() ? '#000' : DIM, fontSize: 13,
                      fontWeight: 700, cursor: presetName.trim() ? 'pointer' : 'not-allowed',
                    }}>Save</button>
                  </div>
                </div>

                {/* Saved Presets */}
                {savedPresets.length > 0 && (
                  <div style={{ marginBottom: 18 }}>
                    <label style={{ ...lbl, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 }}>Saved Presets</label>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                      {savedPresets.map((p, i) => (
                        <div key={i} style={{
                          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                          background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 10, padding: '8px 12px',
                        }}>
                          <button onClick={() => { applyFilterState(p.filter); }} style={{
                            background: 'none', border: 'none', color: TEXT, fontSize: 13,
                            fontWeight: 600, cursor: 'pointer', padding: 0, textAlign: 'left', flex: 1,
                          }}>{p.name}</button>
                          <button onClick={() => deletePreset(i)} style={{
                            background: 'none', border: 'none', color: DIM, cursor: 'pointer',
                            padding: '0 0 0 8px', fontSize: 16, lineHeight: 1, opacity: 0.6,
                          }}>&times;</button>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Drawer footer */}
              <div style={{
                padding: '14px 18px', borderTop: `1px solid ${BORDER}`,
                display: 'flex', gap: 10, position: 'sticky', bottom: 0, background: '#07101C',
              }}>
                <button onClick={() => { clearAllFilters(); }} style={{
                  flex: 1, background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 10,
                  padding: '12px', color: DIM, fontSize: 14, fontWeight: 600, cursor: 'pointer',
                }}>Reset</button>
                <button onClick={() => setDrawerOpen(false)} style={{
                  flex: 1, background: GOLD, border: 'none', borderRadius: 10,
                  padding: '12px', color: '#000', fontSize: 14, fontWeight: 700, cursor: 'pointer',
                }}>Apply &amp; Close</button>
              </div>
            </div>
          </div>
        )}

        {/* Active filter chips below the bar */}
        {activeFilterCount > 0 && (
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 10 }}>
            {filterStatuses.map(s => (
              <span key={s} style={chipStyle}>
                {s} <span onClick={() => setFilterStatuses(prev => prev.filter(v => v !== s))} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            ))}
            {filterPriorities.map(p => (
              <span key={p} style={{ ...chipStyle, background: `rgba(${hexRgb(priorityColor(p))},.12)`, borderColor: `rgba(${hexRgb(priorityColor(p))},.3)`, color: priorityColor(p) }}>
                {p} <span onClick={() => setFilterPriorities(prev => prev.filter(v => v !== p))} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            ))}
            {filterAssignee && (
              <span style={chipStyle}>
                Assigned: {filterAssignee} <span onClick={() => setFilterAssignee('')} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            )}
            {(filterDateFrom || filterDateTo) && (
              <span style={chipStyle}>
                Created: {filterDateFrom || '...'} - {filterDateTo || '...'} <span onClick={() => { setFilterDateFrom(''); setFilterDateTo(''); }} style={{ cursor: 'pointer', marginLeft: 2, fontSize: 13 }}>&times;</span>
              </span>
            )}
          </div>
        )}

        {loading ? (
          <div style={{ textAlign: 'center', padding: '40px 0', color: DIM }}>Loading RFIs...</div>
        ) : rfis.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '40px 16px', color: DIM }}>
            <div style={{ marginBottom: 8, color: PURPLE, display: 'flex', justifyContent: 'center' }}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={40} height={40}>
                <circle cx={12} cy={12} r={10}/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1={12} y1={17} x2={12.01} y2={17}/>
              </svg>
            </div>
            <p style={{ margin: 0, fontSize: 14 }}>No RFIs yet. Tap "+ New RFI" to create one.</p>
          </div>
        ) : (
          <>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {filteredRfis.map((rfi) => {
              const sc = statusColor(rfi.status);
              const isOverdue = rfi.due_date && new Date(rfi.due_date) < new Date() && rfi.status?.toLowerCase() !== 'answered' && rfi.status?.toLowerCase() !== 'closed' && rfi.status?.toLowerCase() !== 'resolved';
              const isChecked = selectedIds.has(rfi.id);
              return (
                <button
                  key={rfi.id}
                  onClick={() => selectMode ? toggleSelectId(rfi.id) : openDetail(rfi)}
                  style={{
                    background: isChecked ? 'rgba(139,92,246,.08)' : RAISED,
                    border: `1px solid ${isChecked ? PURPLE : isOverdue ? 'rgba(239,68,68,.35)' : BORDER}`,
                    borderRadius: 14, padding: '14px', textAlign: 'left', width: '100%', cursor: 'pointer',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }}>
                    {selectMode && (
                      <div style={{
                        width: 22, height: 22, borderRadius: 6, border: `2px solid ${isChecked ? PURPLE : BORDER}`,
                        background: isChecked ? PURPLE : 'transparent', display: 'flex', alignItems: 'center',
                        justifyContent: 'center', flexShrink: 0, marginTop: 2,
                      }}>
                        {isChecked && <svg viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth={3} strokeLinecap="round" strokeLinejoin="round" width={14} height={14}><polyline points="20 6 9 17 4 12"/></svg>}
                      </div>
                    )}
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                        {rfi.rfi_number != null && (
                          <span style={{ fontSize: 11, fontWeight: 800, color: GOLD, background: 'rgba(212,160,23,.12)', padding: '2px 8px', borderRadius: 6 }}>
                            RFI-{rfi.rfi_number}
                          </span>
                        )}
                        <span style={{
                          fontSize: 11, fontWeight: 700, padding: '2px 8px', borderRadius: 6,
                          background: `rgba(${hexRgb(isOverdue ? RED : sc)},.12)`,
                          color: isOverdue ? RED : sc,
                        }}>
                          {isOverdue ? 'Overdue' : rfi.status}
                        </span>
                        {rfi.priority && (
                          <span style={{
                            fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 6,
                            background: `rgba(${hexRgb(priorityColor(rfi.priority))},.12)`,
                            color: priorityColor(rfi.priority),
                          }}>
                            {rfi.priority}
                          </span>
                        )}
                      </div>
                      <p style={{ margin: '0 0 4px', fontSize: 15, fontWeight: 700, color: TEXT, lineHeight: 1.3 }}>{rfi.subject}</p>
                      <p style={{ margin: 0, fontSize: 12, color: DIM }}>
                        {rfi.due_date ? `Due ${formatDate(rfi.due_date)}` : 'No due date'}
                        {rfi.spec_section ? ` · ${rfi.spec_section}` : ''}
                        {rfi.assigned_to ? ` · ${rfi.assigned_to}` : ''}
                      </p>
                    </div>
                    {!selectMode && <span style={{ color: DIM, fontSize: 18, flexShrink: 0, marginTop: 4 }}>›</span>}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Bulk Action Bar */}
          {selectMode && selectedIds.size > 0 && (
            <div style={{
              position: 'fixed', bottom: 0, left: 0, right: 0, background: '#0A1929',
              borderTop: `1px solid ${BORDER}`, padding: '12px 16px', display: 'flex', gap: 8,
              justifyContent: 'center', zIndex: 100,
            }}>
              <button onClick={() => setConfirmDialog({
                title: 'Close Selected RFIs',
                message: `Are you sure you want to close ${selectedIds.size} RFI(s)? This action cannot be undone.`,
                action: handleBulkClose,
              })} disabled={bulkProcessing} style={{
                background: 'rgba(34,197,94,.15)', border: `1px solid rgba(34,197,94,.3)`, borderRadius: 10,
                padding: '10px 14px', color: GREEN, fontSize: 12, fontWeight: 700, cursor: 'pointer', flex: 1,
              }}>
                Close ({selectedIds.size})
              </button>
              <button onClick={() => setShowReassignPicker(true)} disabled={bulkProcessing} style={{
                background: 'rgba(59,130,246,.15)', border: `1px solid rgba(59,130,246,.3)`, borderRadius: 10,
                padding: '10px 14px', color: BLUE, fontSize: 12, fontWeight: 700, cursor: 'pointer', flex: 1,
              }}>
                Reassign ({selectedIds.size})
              </button>
              <button onClick={() => handleBulkExport()} disabled={bulkProcessing} style={{
                background: 'rgba(212,160,23,.15)', border: `1px solid rgba(212,160,23,.3)`, borderRadius: 10,
                padding: '10px 14px', color: GOLD, fontSize: 12, fontWeight: 700, cursor: 'pointer', flex: 1,
              }}>
                Export ({selectedIds.size})
              </button>
            </div>
          )}

          {/* Reassign Picker Modal */}
          {showReassignPicker && (
            <div style={{
              position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,.12)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200, padding: 20,
            }}>
              <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 16, padding: 24, width: '100%', maxWidth: 400 }}>
                <h3 style={{ margin: '0 0 14px', fontSize: 18, fontWeight: 800, color: TEXT }}>Reassign {selectedIds.size} RFI(s)</h3>
                <label style={lbl}>Assign To</label>
                <input value={reassignTo} onChange={(e) => setReassignTo(e.target.value)} placeholder="Enter assignee name or email" style={inp} />
                <div style={{ display: 'flex', gap: 10, marginTop: 16 }}>
                  <button onClick={() => { setShowReassignPicker(false); setReassignTo(''); }} style={{
                    flex: 1, background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 10,
                    padding: '12px', color: DIM, fontSize: 14, cursor: 'pointer',
                  }}>Cancel</button>
                  <button onClick={handleBulkReassign} disabled={bulkProcessing || !reassignTo.trim()} style={{
                    flex: 1, background: bulkProcessing ? '#1E3A5F' : BLUE, border: 'none', borderRadius: 10,
                    padding: '12px', color: bulkProcessing ? DIM : '#fff', fontSize: 14, fontWeight: 700, cursor: bulkProcessing ? 'wait' : 'pointer',
                  }}>{bulkProcessing ? 'Reassigning...' : 'Reassign'}</button>
                </div>
              </div>
            </div>
          )}

          {/* Confirmation Dialog */}
          {confirmDialog && (
            <div style={{
              position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,.12)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200, padding: 20,
            }}>
              <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 16, padding: 24, width: '100%', maxWidth: 400 }}>
                <h3 style={{ margin: '0 0 8px', fontSize: 18, fontWeight: 800, color: TEXT }}>{confirmDialog.title}</h3>
                <p style={{ margin: '0 0 20px', fontSize: 14, color: DIM, lineHeight: 1.5 }}>{confirmDialog.message}</p>
                <div style={{ display: 'flex', gap: 10 }}>
                  <button onClick={() => setConfirmDialog(null)} style={{
                    flex: 1, background: 'transparent', border: `1px solid ${BORDER}`, borderRadius: 10,
                    padding: '12px', color: DIM, fontSize: 14, cursor: 'pointer',
                  }}>Cancel</button>
                  <button onClick={() => { confirmDialog.action(); setConfirmDialog(null); }} disabled={bulkProcessing} style={{
                    flex: 1, background: RED, border: 'none', borderRadius: 10,
                    padding: '12px', color: '#fff', fontSize: 14, fontWeight: 700, cursor: 'pointer',
                  }}>{bulkProcessing ? 'Processing...' : 'Confirm'}</button>
                </div>
              </div>
            </div>
          )}
          </>
        )}
      </div>
    );
  }

  // ─── DETAIL VIEW ──────────────────────────────────────────────
  if (view === 'detail' && selectedRfi) {
    const sc = statusColor(selectedRfi.status);
    const isOverdue = selectedRfi.due_date && new Date(selectedRfi.due_date) < new Date() && selectedRfi.status?.toLowerCase() !== 'answered' && selectedRfi.status?.toLowerCase() !== 'closed';
    return (
      <div style={{ padding: '18px 16px' }}>
        <button onClick={() => { setView('list'); setSubmitMsg(''); }} style={backBtn}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round" width={22} height={22}>
            <line x1={19} y1={12} x2={5} y2={12}/><polyline points="12 19 5 12 12 5"/>
          </svg>
        </button>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
          {selectedRfi.rfi_number != null && (
            <span style={{ fontSize: 12, fontWeight: 800, color: GOLD, background: 'rgba(212,160,23,.12)', padding: '3px 10px', borderRadius: 6 }}>
              RFI-{selectedRfi.rfi_number}
            </span>
          )}
          <span style={{
            fontSize: 12, fontWeight: 700, padding: '3px 10px', borderRadius: 6,
            background: `rgba(${hexRgb(isOverdue ? RED : sc)},.12)`,
            color: isOverdue ? RED : sc,
          }}>
            {isOverdue ? 'Overdue' : selectedRfi.status}
          </span>
        </div>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <h1 style={{ margin: '0 0 4px', fontSize: 20, fontWeight: 800, color: TEXT }}>{selectedRfi.subject}</h1>
            <p style={{ margin: '0 0 16px', fontSize: 12, color: DIM }}>
              {selectedRfi.due_date ? `Due ${formatDate(selectedRfi.due_date)}` : 'No due date'}
              {selectedRfi.spec_section ? ` · ${selectedRfi.spec_section}` : ''}
              {selectedRfi.created_at ? ` · Created ${formatDate(selectedRfi.created_at)}` : ''}
            </p>
          </div>
          <button onClick={() => {
            const rfi = selectedRfi;
            const responsesHtml = (rfi.responses || []).map(r =>
              `<tr><td>${r.author}</td><td>${r.text}</td><td>${formatDate(r.created_at)}</td></tr>`
            ).join('');
            const attachmentsHtml = (rfi.attachments || []).map(a =>
              `<li><a href="${a.url}">${a.name}</a></li>`
            ).join('');
            exportPDF(`RFI-${rfi.rfi_number || ''} ${rfi.subject}`, `
              <h1>RFI${rfi.rfi_number != null ? '-' + rfi.rfi_number : ''}: ${rfi.subject}</h1>
              <table>
                <tr><th>Status</th><td><span class="badge">${rfi.status}</span></td></tr>
                <tr><th>Spec Section</th><td>${rfi.spec_section || '—'}</td></tr>
                <tr><th>Due Date</th><td>${formatDate(rfi.due_date)}</td></tr>
                <tr><th>Created</th><td>${formatDate(rfi.created_at)}</td></tr>
              </table>
              <h2>Question</h2>
              <div class="section"><p>${(rfi.question || '').replace(/\n/g, '<br/>')}</p></div>
              ${attachmentsHtml ? `<h2>Attachments</h2><ul>${attachmentsHtml}</ul>` : ''}
              ${(rfi.responses || []).length > 0 ? `
                <h2>Responses (${rfi.responses!.length})</h2>
                <table><tr><th>Author</th><th>Response</th><th>Date</th></tr>${responsesHtml}</table>
              ` : '<h2>Responses</h2><p class="meta">No responses yet</p>'}
            `);
          }} style={{
            background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 10,
            padding: '8px 14px', color: DIM, fontSize: 13, fontWeight: 600, cursor: 'pointer',
            display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0,
          }}>
            <PdfIcon /> Export PDF
          </button>
          <button onClick={() => setShowEmail(true)} style={{
            background: 'rgba(212,160,23,.1)', border: '1px solid rgba(212,160,23,.3)', borderRadius: 10,
            padding: '8px 14px', color: GOLD, fontSize: 13, fontWeight: 600, cursor: 'pointer',
            display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0,
          }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}>
              <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/>
            </svg>
            Email
          </button>
        </div>

        {showEmail && (
          <EmailComposer
            projectId={projectId}
            onClose={() => setShowEmail(false)}
            onSent={() => { setShowEmail(false); setSubmitMsg('Email sent successfully'); setTimeout(() => setSubmitMsg(''), 3500); }}
            defaultSubject={`RFI #${selectedRfi.rfi_number || ''} - ${selectedRfi.subject}`}
            defaultBody={[
              `RFI #${selectedRfi.rfi_number || ''}: ${selectedRfi.subject}`,
              `Status: ${selectedRfi.status}`,
              selectedRfi.spec_section ? `Spec Section: ${selectedRfi.spec_section}` : '',
              selectedRfi.due_date ? `Due Date: ${formatDate(selectedRfi.due_date)}` : '',
              '',
              'Question:',
              selectedRfi.question,
              '',
              ...(selectedRfi.responses && selectedRfi.responses.length > 0
                ? ['Responses:', ...selectedRfi.responses.map(r => `- ${r.author} (${formatDate(r.created_at)}): ${r.text}`)]
                : ['No responses yet.']),
            ].filter(Boolean).join('\n')}
            module="rfis"
            itemId={selectedRfi.id}
            itemTitle={selectedRfi.subject}
          />
        )}

        {submitMsg && (
          <div style={{ background: 'rgba(34,197,94,.1)', border: '1px solid rgba(34,197,94,.3)', borderRadius: 10, padding: '12px 14px', marginBottom: 14, color: GREEN, fontSize: 14, fontWeight: 600 }}>
            {submitMsg}
          </div>
        )}

        {/* Question */}
        <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px', marginBottom: 14 }}>
          <p style={{ margin: '0 0 8px', fontSize: 11, fontWeight: 700, color: DIM, textTransform: 'uppercase', letterSpacing: 0.8 }}>Question</p>
          <p style={{ margin: 0, fontSize: 14, color: TEXT, lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{selectedRfi.question}</p>
        </div>

        {/* Attachments */}
        {selectedRfi.attachments && selectedRfi.attachments.length > 0 && (
          <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px', marginBottom: 14 }}>
            <p style={{ margin: '0 0 8px', fontSize: 11, fontWeight: 700, color: DIM, textTransform: 'uppercase', letterSpacing: 0.8 }}>Attachments</p>
            {selectedRfi.attachments.map((att, i) => (
              <a key={i} href={att.url} target="_blank" rel="noopener noreferrer" style={{
                display: 'flex', alignItems: 'center', gap: 8, padding: '8px 0',
                borderTop: i > 0 ? `1px solid ${BORDER}` : 'none', textDecoration: 'none',
              }}>
                <svg viewBox="0 0 24 24" fill="none" stroke={BLUE} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}>
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/>
                </svg>
                <span style={{ fontSize: 13, color: BLUE, fontWeight: 600 }}>{att.name}</span>
              </a>
            ))}
          </div>
        )}

        {/* Response History */}
        <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px', marginBottom: 14 }}>
          <p style={{ margin: '0 0 8px', fontSize: 11, fontWeight: 700, color: DIM, textTransform: 'uppercase', letterSpacing: 0.8 }}>
            Responses ({selectedRfi.responses?.length || 0})
          </p>
          {(!selectedRfi.responses || selectedRfi.responses.length === 0) ? (
            <p style={{ margin: 0, fontSize: 13, color: DIM, fontStyle: 'italic' }}>No responses yet</p>
          ) : (
            selectedRfi.responses.map((resp, i) => (
              <div key={i} style={{ padding: '10px 0', borderTop: i > 0 ? `1px solid ${BORDER}` : 'none' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                  <span style={{ fontSize: 13, fontWeight: 700, color: GOLD }}>{resp.author}</span>
                  <span style={{ fontSize: 11, color: DIM }}>{formatDate(resp.created_at)}</span>
                </div>
                <p style={{ margin: 0, fontSize: 14, color: TEXT, lineHeight: 1.5, whiteSpace: 'pre-wrap' }}>{resp.text}</p>
                {resp.attachments && resp.attachments.length > 0 && (
                  <div style={{ marginTop: 6 }}>
                    {resp.attachments.map((att, j) => (
                      <a key={j} href={att.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: 12, color: BLUE, textDecoration: 'none', display: 'block', marginTop: 2 }}>
                        {att.name}
                      </a>
                    ))}
                  </div>
                )}
              </div>
            ))
          )}
        </div>

        {/* Response Form */}
        <form onSubmit={handleRespond} style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px', marginBottom: 14 }}>
          <p style={{ margin: '0 0 10px', fontSize: 11, fontWeight: 700, color: DIM, textTransform: 'uppercase', letterSpacing: 0.8 }}>Add Response</p>
          <textarea
            value={responseText}
            onChange={(e) => setResponseText(e.target.value)}
            placeholder="Type your response..."
            rows={4}
            style={inp}
            required
          />
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 10 }}>
            <button type="button" onClick={() => photoInputRef.current?.click()} style={{
              background: 'rgba(59,130,246,.1)', border: `1px solid rgba(59,130,246,.3)`,
              borderRadius: 8, padding: '8px 14px', color: BLUE, fontSize: 13, fontWeight: 600, cursor: 'pointer',
              display: 'flex', alignItems: 'center', gap: 6,
            }}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" width={16} height={16}>
                <rect x={3} y={3} width={18} height={18} rx={2}/><circle cx={8.5} cy={8.5} r={1.5}/><polyline points="21 15 16 10 5 21"/>
              </svg>
              {responsePhoto ? responsePhoto.name : 'Attach Photo'}
            </button>
            <input ref={photoInputRef} type="file" accept="image/*" capture="environment" style={{ display: 'none' }} onChange={(e) => setResponsePhoto(e.target.files?.[0] || null)} />
          </div>
          <button type="submit" disabled={submitting} style={{
            width: '100%', background: submitting ? '#1E3A5F' : GREEN, border: 'none', borderRadius: 14,
            padding: '16px', color: submitting ? DIM : '#000', fontSize: 16, fontWeight: 800,
            cursor: submitting ? 'wait' : 'pointer', marginTop: 12,
          }}>
            {submitting ? 'Submitting...' : online ? 'Submit Response' : 'Submit (Offline — will sync)'}
          </button>
        </form>
      </div>
    );
  }

  // ─── CREATE VIEW ──────────────────────────────────────────────
  return (
    <div style={{ padding: '18px 16px' }}>
      <button onClick={() => { setView('list'); setSubmitMsg(''); }} style={backBtn}>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round" width={22} height={22}>
          <line x1={19} y1={12} x2={5} y2={12}/><polyline points="12 19 5 12 12 5"/>
        </svg>
      </button>
      <h1 style={{ margin: '0 0 2px', fontSize: 22, fontWeight: 800, color: PURPLE }}>New RFI</h1>
      <p style={{ margin: '0 0 18px', fontSize: 13, color: DIM }}>Request for information — office responds in dashboard</p>

      {!online && <div style={{ background: 'rgba(239,68,68,.1)', border: '1px solid rgba(239,68,68,.25)', borderRadius: 8, padding: '8px 12px', marginBottom: 14, fontSize: 13, color: RED, fontWeight: 600 }}>Offline — will queue and sync automatically</div>}

      <form onSubmit={handleCreate}>
        <div style={{ background: RAISED, border: `1px solid ${BORDER}`, borderRadius: 14, padding: '14px 14px 6px', marginBottom: 12 }}>
          <p style={{ margin: '0 0 10px', fontSize: 11, fontWeight: 700, color: DIM, textTransform: 'uppercase', letterSpacing: 0.8 }}>RFI Details</p>

          <div style={{ marginBottom: 10 }}>
            <label style={lbl}>Subject *</label>
            <input value={newSubject} onChange={(e) => setNewSubject(e.target.value)} placeholder="Brief description" style={inp} required />
          </div>

          <div style={{ marginBottom: 10 }}>
            <label style={lbl}>Question / Description *</label>
            <textarea value={newQuestion} onChange={(e) => setNewQuestion(e.target.value)} placeholder="Describe the issue and what clarification you need..." rows={4} style={inp} required />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 10 }}>
            <div>
              <label style={lbl}>Spec Section</label>
              <select value={newSpec} onChange={(e) => setNewSpec(e.target.value)} style={inp}>
                {SPEC_SECTIONS.map((s) => <option key={s} value={s} style={{ background: '#0D1D2E' }}>{s}</option>)}
              </select>
            </div>
            <div>
              <label style={lbl}>Need By</label>
              <input type="date" value={newDueDate} onChange={(e) => setNewDueDate(e.target.value)} style={inp} />
            </div>
          </div>
        </div>

        <button type="submit" disabled={submitting} style={{
          width: '100%', background: submitting ? '#1E3A5F' : PURPLE, border: 'none', borderRadius: 14,
          padding: '18px', color: submitting ? DIM : '#fff', fontSize: 17, fontWeight: 800,
          cursor: submitting ? 'wait' : 'pointer', marginTop: 4,
        }}>
          {submitting ? 'Saving...' : online ? 'File RFI' : 'File RFI (Offline — will sync)'}
        </button>
      </form>
    </div>
  );
}

export default function FieldRFIsPage() {
  return (
    <Suspense fallback={<div style={{ padding: 32, color: '#8BAAC8', textAlign: 'center' }}>Loading...</div>}>
      <RFIsPage />
    </Suspense>
  );
}

const backBtn: React.CSSProperties = { background: 'none', border: 'none', color: DIM, cursor: 'pointer', padding: '8px', marginLeft: -8, display: 'flex', alignItems: 'center', marginBottom: 4 };
const lbl: React.CSSProperties = { display: 'block', fontSize: 12, color: DIM, marginBottom: 4, fontWeight: 600 };
const inp: React.CSSProperties = { width: '100%', background: '#07101C', border: '1px solid #1E3A5F', borderRadius: 10, padding: '11px 14px', color: '#F0F4FF', fontSize: 15, outline: 'none' };

function hexRgb(hex: string): string {
  const r = parseInt((hex || '#888').slice(1, 3), 16);
  const g = parseInt((hex || '#888').slice(3, 5), 16);
  const b = parseInt((hex || '#888').slice(5, 7), 16);
  return `${r},${g},${b}`;
}
